import assert from "node:assert/strict";
import test from "node:test";
import { hash } from "@node-rs/argon2";
import { assertModuleEntitled,authorizeResolvedActor } from "../server/auth/authorization.ts";
import { assertSameOrigin,csrfCookie,sessionCookie } from "../server/auth/cookies.ts";
import { privacyHash,randomToken,sha256 } from "../server/auth/crypto.ts";
import { hashPassword,validatePassword,verifyPassword } from "../server/auth/password.ts";
import { policies } from "../server/auth/policies.ts";
import { authRateLimit } from "../server/auth/rate-limit.ts";
import type { AuthenticatedActor } from "../server/auth/types.ts";

const tenant="30000000-0000-4000-8000-000000000001";
function actor(overrides:Partial<AuthenticatedActor>={}):AuthenticatedActor{return{userId:"10000000-0000-4000-8000-000000000002",email:"user@example.com",displayName:"User",fullName:"User",sessionId:"90000000-0000-4000-8000-000000000001",csrfHash:sha256("csrf"),activeTenantId:tenant,identityType:"school",platformPermissions:new Set(),rolePermissions:new Set(["students.view","students.manage","academics.view","operations.view","operations.manage","workspace.view","workspace.manage","settings.view","settings.manage","roles.view","roles.manage"]),moduleEntitlements:new Set(["student_information","academics","attendance","fees_finance","settings_billing","access_control"]),membershipStatus:"active",...overrides};}

test("Argon2id password hashes verify and outdated parameters require rehash",async()=>{const password="A long Unicode passphrase विद्यालय 2026";const current=await hashPassword(password);assert.match(current,/^\$argon2id\$v=19\$m=65536,t=3,p=1\$/);assert.deepEqual(await verifyPassword(current,password),{valid:true,needsRehash:false});const old=await hash(password,{algorithm:2,version:1,memoryCost:32768,timeCost:2,parallelism:1,outputLen:32});assert.deepEqual(await verifyPassword(old,password),{valid:true,needsRehash:true});assert.equal((await verifyPassword(current,"incorrect passphrase")).valid,false);});
test("password policy accepts passphrases and rejects bounds and common values",()=>{assert.deepEqual(validatePassword("valid passphrase विद्यालय"),[]);assert.ok(validatePassword("too short").length);assert.ok(validatePassword("x".repeat(129)).length);assert.ok(validatePassword("password123").length);});
test("session and CSRF tokens are independent 256-bit values and cookies are hardened",()=>{const session=randomToken(),csrf=randomToken();assert.notEqual(session,csrf);assert.equal(Buffer.from(session,"base64url").length,32);assert.match(sessionCookie(session),/__Host-hig_session=.*Path=\/.*HttpOnly.*Secure.*SameSite=Lax/);assert.match(csrfCookie(csrf),/__Host-hig_csrf=.*Path=\/.*Secure.*SameSite=Lax/);assert.doesNotMatch(csrfCookie(csrf),/HttpOnly/);});
test("same-origin mutation validation rejects missing, cross-scheme and forged origins",()=>{assert.doesNotThrow(()=>assertSameOrigin(new Request("https://school.example/api",{method:"POST",headers:{origin:"https://school.example",host:"school.example"}})));assert.throws(()=>assertSameOrigin(new Request("https://school.example/api",{method:"POST",headers:{origin:"http://school.example",host:"school.example"}})));assert.throws(()=>assertSameOrigin(new Request("https://school.example/api",{method:"POST",headers:{origin:"https://evil.example",host:"school.example"}})));assert.throws(()=>assertSameOrigin(new Request("https://school.example/api",{method:"POST",headers:{host:"school.example"}})));});
test("central authorization rejects missing, wrong-scope, cross-tenant, inactive, unentitled and unpermitted actors",()=>{assert.throws(()=>authorizeResolvedActor(null,policies.studentsView,tenant));assert.throws(()=>authorizeResolvedActor(actor({identityType:"platform",activeTenantId:null}),policies.studentsView,tenant));assert.throws(()=>authorizeResolvedActor(actor(),policies.studentsView,"30000000-0000-4000-8000-000000000099"));assert.throws(()=>authorizeResolvedActor(actor({membershipStatus:"suspended"}),policies.studentsView,tenant));assert.throws(()=>authorizeResolvedActor(actor({moduleEntitlements:new Set()}),policies.studentsView,tenant));assert.throws(()=>authorizeResolvedActor(actor({rolePermissions:new Set()}),policies.studentsView,tenant));assert.equal(authorizeResolvedActor(actor(),policies.studentsView,tenant).userId,actor().userId);});
test("platform permissions never grant school access and school permissions never grant platform access",()=>{const platform=actor({identityType:"platform",activeTenantId:null,membershipStatus:null,platformPermissions:new Set(["platform.schools.view"])});assert.equal(authorizeResolvedActor(platform,policies.schoolsList).identityType,"platform");assert.throws(()=>authorizeResolvedActor(platform,policies.studentsView,tenant));assert.throws(()=>authorizeResolvedActor(actor(),policies.schoolsList));});
test("module labels resolve to the same canonical tenant entitlements",()=>{const entitled=actor({moduleEntitlements:new Set(["fees_finance","communication","examinations","attendance"])});assert.doesNotThrow(()=>assertModuleEntitled(entitled,"Finance & Fees"));assert.doesNotThrow(()=>assertModuleEntitled(entitled,"Communicate"));assert.doesNotThrow(()=>assertModuleEntitled(entitled,"Online Examinations"));assert.doesNotThrow(()=>assertModuleEntitled(entitled,"QR Code Attendance"));assert.throws(()=>assertModuleEntitled(entitled,"Transport"));});
test("high-risk operations remain blocked without step-up",()=>{assert.throws(()=>authorizeResolvedActor(actor(),policies.configurationManage,tenant),/Step-up/);assert.throws(()=>authorizeResolvedActor(actor(),policies.rolesManage,tenant),/Step-up/);});
test("local auth limiter enforces concurrent burst counters",async()=>{const id=crypto.randomUUID();const results=await Promise.all(Array.from({length:6},()=>authRateLimit("login",`${id}@example.com`,`ip-${id}`,{NODE_ENV:"test",HIG_REDIS_NAMESPACE:`test:${id}:`})));assert.equal(results.filter(result=>result.allowed).length,5);assert.equal(results.at(-1)?.retryAfter,60);});
test("protected authentication throttles fail closed without Redis in staging and production",async()=>{await assert.rejects(authRateLimit("login","user@example.com","198.51.100.8",{NODE_ENV:"production"}),/unavailable/);await assert.rejects(authRateLimit("reset","user@example.com","198.51.100.8",{NODE_ENV:"test",HIG_DEPLOYMENT_ENV:"staging"}),/unavailable/);});
test("security telemetry hashing fails closed without a deployment secret",()=>{const previousNode=process.env.NODE_ENV,previousDeployment=process.env.HIG_DEPLOYMENT_ENV,previousHash=process.env.HIG_SECURITY_HASH_KEY,previousSession=process.env.SESSION_SECRET;try{Object.assign(process.env,{NODE_ENV:"production"});delete process.env.HIG_DEPLOYMENT_ENV;delete process.env.HIG_SECURITY_HASH_KEY;delete process.env.SESSION_SECRET;assert.throws(()=>privacyHash("198.51.100.9"),/unavailable/);process.env.HIG_SECURITY_HASH_KEY="unique-test-security-hash-key";assert.equal(privacyHash("same"),privacyHash("same"));assert.notEqual(privacyHash("same"),sha256("same"));}finally{restore("NODE_ENV",previousNode);restore("HIG_DEPLOYMENT_ENV",previousDeployment);restore("HIG_SECURITY_HASH_KEY",previousHash);restore("SESSION_SECRET",previousSession);}});
function restore(name:string,value:string|undefined){if(value===undefined)delete process.env[name];else process.env[name]=value;}
