import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:http/http.dart' as http;

const apiBase=String.fromEnvironment('API_BASE_URL',defaultValue:'http://10.0.2.2:3002');
const demoEmail=String.fromEnvironment('HIG_DEMO_EMAIL');
const demoPassword=String.fromEnvironment('HIG_DEMO_PASSWORD');
void main()=>runApp(const DriverApp());
class DriverApp extends StatelessWidget{const DriverApp({super.key});@override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData.dark(useMaterial3:true).copyWith(colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xffe94e0c),brightness:Brightness.dark)),home:const DriverHome());}
class DriverHome extends StatefulWidget{const DriverHome({super.key});@override State<DriverHome> createState()=>_DriverHomeState();}
class _DriverHomeState extends State<DriverHome>{String token='';Map<String,dynamic>? driver;StreamSubscription<Position>? subscription;bool tracking=false;String message='Ready to start';
  @override void initState(){super.initState();login();}
  Future<void> login()async{if(demoEmail.isEmpty||demoPassword.isEmpty)throw Exception('Sales-demo credentials were not supplied at build time');final response=await http.post(Uri.parse('$apiBase/api/v1/demo/login'),headers:{'content-type':'application/json'},body:jsonEncode({'email':demoEmail,'password':demoPassword}));final body=jsonDecode(response.body);if(response.statusCode!=200)throw Exception(body['error']??'Login failed');token=body['token'];await refresh();}
  Future<void> refresh()async{final response=await http.get(Uri.parse('$apiBase/api/v1/demo/state'),headers:{'authorization':'Bearer $token'});final body=jsonDecode(response.body);if(mounted)setState(()=>driver=body['driver']);}
  Future<void> send(Position position)async{await http.post(Uri.parse('$apiBase/api/v1/demo/action'),headers:{'content-type':'application/json','authorization':'Bearer $token'},body:jsonEncode({'action':'update_gps','latitude':position.latitude,'longitude':position.longitude,'speedKph':position.speed*3.6,'heading':position.heading,'tripStatus':'in_progress'}));await refresh();}
  Future<void> toggle()async{if(tracking){await subscription?.cancel();subscription=null;setState((){tracking=false;message='Trip paused';});return;}final enabled=await Geolocator.isLocationServiceEnabled();if(!enabled){setState(()=>message='Enable device location services');return;}var permission=await Geolocator.checkPermission();if(permission==LocationPermission.denied)permission=await Geolocator.requestPermission();if(permission==LocationPermission.denied||permission==LocationPermission.deniedForever){setState(()=>message='Location permission is required');return;}subscription=Geolocator.getPositionStream(locationSettings:const LocationSettings(accuracy:LocationAccuracy.high,distanceFilter:10)).listen(send);setState((){tracking=true;message='Live location streaming';});}
  Future<void> complete()async{await subscription?.cancel();subscription=null;final d=driver;if(d==null)return;await http.post(Uri.parse('$apiBase/api/v1/demo/action'),headers:{'content-type':'application/json','authorization':'Bearer $token'},body:jsonEncode({'action':'update_gps','latitude':d['latitude'],'longitude':d['longitude'],'speedKph':0,'heading':d['heading'],'tripStatus':'completed'}));setState((){tracking=false;message='Trip completed';});await refresh();}
  @override void dispose(){subscription?.cancel();super.dispose();}
  @override Widget build(BuildContext context){final d=driver;if(d==null)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Scaffold(appBar:AppBar(title:const Text('Hig Driver GPS'),actions:[IconButton(onPressed:refresh,icon:const Icon(Icons.sync))]),body:ListView(padding:const EdgeInsets.all(18),children:[Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(borderRadius:BorderRadius.circular(18),gradient:const LinearGradient(colors:[Color(0xff15364b),Color(0xff137b7c)])),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('ASSIGNED TRIP',style:TextStyle(color:Color(0xff8ee2da),fontSize:10)),Text(d['route'],style:const TextStyle(fontSize:25,fontWeight:FontWeight.w800)),Text(d['vehicle'],style:const TextStyle(color:Color(0xffbdd9db))),const SizedBox(height:25),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('${(d['speedKph'] as num).round()} km/h',style:const TextStyle(fontSize:30,fontWeight:FontWeight.w800)),Chip(label:Text('${d['tripStatus']}'.replaceAll('_',' ').toUpperCase()))])]))),const SizedBox(height:16),Container(height:320,decoration:BoxDecoration(color:const Color(0xff1a2836),borderRadius:BorderRadius.circular(18)),child:Stack(children:[const Center(child:Icon(Icons.map_outlined,size:120,color:Color(0xff30475a))),Center(child:Container(width:62,height:62,decoration:const BoxDecoration(color:Color(0xffff6f22),shape:BoxShape.circle),child:const Icon(Icons.directions_bus,color:Colors.white,size:32))),Positioned(left:16,right:16,bottom:16,child:Card(color:const Color(0xff101923),child:Padding(padding:const EdgeInsets.all(13),child:Text('${d['latitude']}, ${d['longitude']}\\n$message'))))])),const SizedBox(height:16),FilledButton.icon(onPressed:toggle,icon:Icon(tracking?Icons.pause:Icons.play_arrow),label:Padding(padding:const EdgeInsets.all(14),child:Text(tracking?'Pause live tracking':'Start live trip'))),const SizedBox(height:9),OutlinedButton.icon(onPressed:complete,icon:const Icon(Icons.flag_outlined),label:const Padding(padding:EdgeInsets.all(14),child:Text('Complete trip'))),const SizedBox(height:9),FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:Colors.red),onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Demo SOS recorded. Configure emergency contacts before production.'))),icon:const Icon(Icons.sos),label:const Padding(padding:EdgeInsets.all(14),child:Text('Emergency SOS')))]));}}
