export type RoutePolicy = { scope: "platform" | "tenant"; permission: string; module: string | null; stepUp?: boolean };
export const policies = {
  schoolsList: { scope: "platform", permission: "platform.schools.view", module: null },
  schoolsManage: { scope: "platform", permission: "platform.schools.manage", module: null },
  companyAccessView: { scope: "platform", permission: "platform.schools.view", module: null },
  companyAccessManage: { scope: "platform", permission: "platform.schools.manage", module: null },
  configurationView: { scope: "tenant", permission: "settings.view", module: "settings_billing" },
  configurationManage: { scope: "tenant", permission: "settings.manage", module: "settings_billing", stepUp: true },
  foundationView: { scope: "tenant", permission: "academics.view", module: "academics" },
  foundationManage: { scope: "tenant", permission: "academics.manage", module: "academics" },
  rolesView: { scope: "tenant", permission: "roles.view", module: "access_control" },
  schoolAppAccessView: { scope: "tenant", permission: "roles.view", module: "access_control" },
  rolesManage: { scope: "tenant", permission: "roles.manage", module: "access_control", stepUp: true },
  studentsView: { scope: "tenant", permission: "students.view", module: "student_information" },
  studentsManage: { scope: "tenant", permission: "students.manage", module: "student_information" },
  transportView: { scope: "tenant", permission: "transport.view", module: "transport" },
  transportManage: { scope: "tenant", permission: "transport.manage", module: "transport" },
  operationsView: { scope: "tenant", permission: "resolved_from_operation", module: null },
  operationsManage: { scope: "tenant", permission: "resolved_from_operation", module: null },
  notificationsView: { scope: "tenant", permission: "communication.view", module: "communication" },
  notificationsRead: { scope: "tenant", permission: "communication.view", module: "communication" },
  workspaceView: { scope: "tenant", permission: "resolved_from_module", module: null },
  workspaceManage: { scope: "tenant", permission: "resolved_from_module_and_action", module: null },
} as const satisfies Record<string, RoutePolicy>;
