import { database } from "#db-runtime";
import { SESSION_ABSOLUTE_MS, SESSION_IDLE_MS } from "./cookies.ts";
import { randomToken, sha256 } from "./crypto.ts";
import type { LoginRecord, SessionMetadata } from "./repository.ts";
import type { AuthenticatedActor, SessionCreation } from "./types.ts";

type SessionRow = { id:string; user_id:string; email:string; full_name:string; user_status:string; credential_disabled_at:string|null; active_tenant_id:string|null; credential_version:number; current_version:number; csrf_hash:string; idle_expires_at:string; absolute_expires_at:string; membership_status:string|null; role_key:string|null; platform_role:string|null };
const platformPermissions = new Set(["platform.schools.view", "platform.schools.manage"]);
const now = () => new Date().toISOString();

export async function findLoginRecord(email:string):Promise<LoginRecord|null>{
  const row=await database.prepare(`SELECT u.id userId,u.email,u.full_name fullName,u.status,c.password_hash passwordHash,c.credential_version credentialVersion,c.disabled_at disabledAt,CASE WHEN EXISTS(SELECT 1 FROM platform_role_assignments p WHERE p.user_id=u.id) OR EXISTS(SELECT 1 FROM memberships m WHERE m.user_id=u.id AND m.status='active') THEN 1 ELSE 0 END eligible FROM users u JOIN auth_credentials c ON c.user_id=u.id WHERE lower(u.email)=lower(?) LIMIT 1`).bind(email).first<Record<string,unknown>>();
  return row?{userId:String(row.userId),email:String(row.email),fullName:String(row.fullName),status:String(row.status),passwordHash:String(row.passwordHash),credentialVersion:Number(row.credentialVersion),disabled:Boolean(row.disabledAt),eligible:Boolean(row.eligible)}:null;
}
export async function replacePassword(userId:string,passwordHash:string){const t=now();await database.batch([database.prepare("UPDATE auth_credentials SET password_hash=?,credential_version=credential_version+1,password_changed_at=?,updated_at=? WHERE user_id=?").bind(passwordHash,t,t,userId),database.prepare("UPDATE auth_sessions SET revoked_at=?,revoke_reason='password_changed' WHERE user_id=? AND revoked_at IS NULL").bind(t,userId)]);}
async function firstTenant(userId:string){return (await database.prepare("SELECT tenant_id FROM memberships WHERE user_id=? AND status='active' ORDER BY created_at LIMIT 1").bind(userId).first<{tenant_id:string}>())?.tenant_id??null;}
async function activeTenant(userId:string,tenantId:string){return (await database.prepare("SELECT tenant_id FROM memberships WHERE user_id=? AND tenant_id=? AND status='active' LIMIT 1").bind(userId,tenantId).first<{tenant_id:string}>())?.tenant_id??null;}
export async function createSession(userId:string,credentialVersion:number,activeTenantId:string|null,metadata:SessionMetadata):Promise<SessionCreation>{
  const token=randomToken(),csrfToken=randomToken(),issued=new Date(),id=crypto.randomUUID();
  const platform=await database.prepare("SELECT 1 ok FROM platform_role_assignments WHERE user_id=? LIMIT 1").bind(userId).first();
  const tenant=activeTenantId?await activeTenant(userId,activeTenantId):(platform?null:await firstTenant(userId));
  if(!platform&&!tenant)throw new Error("No active identity");
  if(activeTenantId&&tenant!==activeTenantId)throw new Error("Active membership required");
  const absolute=new Date(issued.getTime()+SESSION_ABSOLUTE_MS).toISOString(),idle=new Date(issued.getTime()+SESSION_IDLE_MS).toISOString();
  await database.prepare(`INSERT INTO auth_sessions(id,token_hash,user_id,active_tenant_id,credential_version,csrf_hash,issued_at,last_seen_at,idle_expires_at,absolute_expires_at,ip_hash,user_agent_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,sha256(token),userId,tenant,credentialVersion,sha256(csrfToken),issued.toISOString(),issued.toISOString(),idle,absolute,metadata.ipHash,metadata.userAgentHash).run();
  return{token,csrfToken,sessionId:id,absoluteExpiresAt:absolute};
}
export async function resolveSession(token:string):Promise<AuthenticatedActor|null>{
  const row=await database.prepare(`SELECT s.id,s.user_id,u.email,u.full_name,u.status user_status,c.disabled_at credential_disabled_at,s.active_tenant_id,s.credential_version,c.credential_version current_version,s.csrf_hash,s.idle_expires_at,s.absolute_expires_at,m.status membership_status,m.role_key,(SELECT role_key FROM platform_role_assignments p WHERE p.user_id=u.id LIMIT 1) platform_role FROM auth_sessions s JOIN users u ON u.id=s.user_id JOIN auth_credentials c ON c.user_id=u.id LEFT JOIN memberships m ON m.user_id=u.id AND m.tenant_id=s.active_tenant_id WHERE s.token_hash=? AND s.revoked_at IS NULL LIMIT 1`).bind(sha256(token)).first<SessionRow>();
  const t=Date.now(); if(!row||row.user_status!=="active"||row.credential_disabled_at!==null||row.credential_version!==row.current_version||Date.parse(row.idle_expires_at)<=t||Date.parse(row.absolute_expires_at)<=t||(row.active_tenant_id&&row.membership_status!=="active")){if(row)await revokeSession(row.id,"invalid_or_expired");return null;}
  const permissions=new Set<string>(),modules=new Set<string>(); if(row.active_tenant_id&&row.role_key){const rp=await database.prepare("SELECT rp.permission FROM roles r JOIN role_permissions rp ON rp.role_id=r.id WHERE r.tenant_id=? AND r.key=?").bind(row.active_tenant_id,row.role_key).all<{permission:string}>();rp.results.forEach(x=>permissions.add(x.permission));const mp=await database.prepare("SELECT module_key FROM module_policies WHERE tenant_id=? AND enabled=1").bind(row.active_tenant_id).all<{module_key:string}>();mp.results.forEach(x=>modules.add(x.module_key));}
  await database.prepare("UPDATE auth_sessions SET last_seen_at=?,idle_expires_at=? WHERE id=?").bind(now(),new Date(t+SESSION_IDLE_MS).toISOString(),row.id).run();
  return{userId:row.user_id,email:row.email,displayName:row.full_name,fullName:row.full_name,sessionId:row.id,csrfHash:row.csrf_hash,activeTenantId:row.active_tenant_id,identityType:row.active_tenant_id?"school":"platform",platformPermissions:!row.active_tenant_id&&row.platform_role?platformPermissions:new Set(),rolePermissions:permissions,moduleEntitlements:modules,membershipStatus:row.membership_status as AuthenticatedActor["membershipStatus"]};
}
export async function rotateTenant(sessionId:string,userId:string,tenantId:string,metadata:SessionMetadata){const member=await database.prepare("SELECT 1 ok FROM memberships WHERE user_id=? AND tenant_id=? AND status='active'").bind(userId,tenantId).first();if(!member)throw new Error("Active membership required");const c=await database.prepare("SELECT credential_version version FROM auth_credentials WHERE user_id=?").bind(userId).first<{version:number}>();await revokeSession(sessionId,"tenant_switch");return createSession(userId,Number(c?.version),tenantId,metadata);}
export async function revokeSession(id:string,reason:string){await database.prepare("UPDATE auth_sessions SET revoked_at=?,revoke_reason=? WHERE id=? AND revoked_at IS NULL").bind(now(),reason,id).run();}
export async function revokeUserSessions(userId:string,reason:string){await database.prepare("UPDATE auth_sessions SET revoked_at=?,revoke_reason=? WHERE user_id=? AND revoked_at IS NULL").bind(now(),reason,userId).run();}
export async function listSessions(userId:string){return(await database.prepare("SELECT id,issued_at issuedAt,last_seen_at lastSeenAt FROM auth_sessions WHERE user_id=? AND revoked_at IS NULL ORDER BY issued_at DESC").bind(userId).all<{id:string;issuedAt:string;lastSeenAt:string}>()).results;}
export async function createReset(email:string,tokenHash:string,ipHash:string|null){const u=await database.prepare("SELECT id,email FROM users WHERE lower(email)=lower(?) AND status='active'").bind(email).first<{id:string;email:string}>();if(!u)return null;const t=now();await database.batch([database.prepare("UPDATE password_reset_tokens SET consumed_at=? WHERE user_id=? AND consumed_at IS NULL").bind(t,u.id),database.prepare("INSERT INTO password_reset_tokens(id,user_id,token_hash,expires_at,requested_at,ip_hash) VALUES(?,?,?,?,?,?)").bind(crypto.randomUUID(),u.id,tokenHash,new Date(Date.now()+30*60_000).toISOString(),t,ipHash)]);return{userId:u.id,email:u.email};}
export async function invalidateReset(tokenHash:string){await database.prepare("UPDATE password_reset_tokens SET consumed_at=? WHERE token_hash=? AND consumed_at IS NULL").bind(now(),tokenHash).run();}
export async function consumeReset(tokenHash:string,passwordHash:string,metadata:SessionMetadata={ipHash:null,userAgentHash:null}){
  const r=await database.prepare("SELECT id,user_id FROM password_reset_tokens WHERE token_hash=? AND consumed_at IS NULL AND expires_at>?").bind(tokenHash,now()).first<{id:string;user_id:string}>();
  if(!r)return null;
  const marker=now(),consumptionHash=sha256(randomToken());
  const result=await database.batch([
    database.prepare("UPDATE password_reset_tokens SET consumed_at=?,token_hash=? WHERE id=? AND consumed_at IS NULL AND expires_at>?").bind(marker,consumptionHash,r.id,marker),
    database.prepare("UPDATE auth_credentials SET password_hash=?,credential_version=credential_version+1,password_changed_at=?,updated_at=? WHERE user_id=? AND EXISTS(SELECT 1 FROM password_reset_tokens WHERE id=? AND token_hash=? AND consumed_at=?)").bind(passwordHash,marker,marker,r.user_id,r.id,consumptionHash,marker),
    database.prepare("UPDATE auth_sessions SET revoked_at=?,revoke_reason='password_reset' WHERE user_id=? AND revoked_at IS NULL AND EXISTS(SELECT 1 FROM password_reset_tokens WHERE id=? AND token_hash=? AND consumed_at=?)").bind(marker,r.user_id,r.id,consumptionHash,marker),
    database.prepare("INSERT INTO audit_events(id,tenant_id,actor_id,action,resource_type,reason,ip_hash,metadata_json,occurred_at) SELECT ?,NULL,?,'auth.password_reset.complete','authentication','success',?,?,? WHERE EXISTS(SELECT 1 FROM password_reset_tokens WHERE id=? AND token_hash=? AND consumed_at=?)").bind(crypto.randomUUID(),r.user_id,metadata.ipHash,JSON.stringify({userAgentHash:metadata.userAgentHash}),marker,r.id,consumptionHash,marker),
  ]);
  return Number(result[0]?.meta?.changes??0)===1?r.user_id:null;
}
export async function acceptInvitation(tokenHash:string,email:string,passwordHash:string,metadata:SessionMetadata={ipHash:null,userAgentHash:null}){
  const i=await database.prepare("SELECT i.id,i.tenant_id,u.id user_id FROM school_invitations i JOIN users u ON lower(u.email)=lower(i.email) WHERE i.token_hash=? AND lower(i.email)=lower(?) AND i.status='pending' AND i.expires_at>?").bind(tokenHash,email,now()).first<{id:string;tenant_id:string;user_id:string}>();
  if(!i)return null;
  const marker=now(),consumptionHash=sha256(randomToken());
  const result=await database.batch([
    database.prepare("UPDATE school_invitations SET status='accepted',token_hash=?,accepted_at=?,updated_at=? WHERE id=? AND status='pending' AND expires_at>?").bind(consumptionHash,marker,marker,i.id,marker),
    database.prepare("INSERT INTO auth_credentials(user_id,password_hash,credential_version,must_change_password,password_changed_at,created_at,updated_at) SELECT ?,?,1,0,?,?,? WHERE EXISTS(SELECT 1 FROM school_invitations WHERE id=? AND token_hash=? AND accepted_at=?) ON CONFLICT(user_id) DO UPDATE SET password_hash=excluded.password_hash,credential_version=auth_credentials.credential_version+1,password_changed_at=excluded.password_changed_at,updated_at=excluded.updated_at").bind(i.user_id,passwordHash,marker,marker,marker,i.id,consumptionHash,marker),
    database.prepare("UPDATE users SET status='active',updated_at=? WHERE id=? AND EXISTS(SELECT 1 FROM school_invitations WHERE id=? AND token_hash=? AND accepted_at=?)").bind(marker,i.user_id,i.id,consumptionHash,marker),
    database.prepare("UPDATE memberships SET status='active',updated_at=? WHERE user_id=? AND tenant_id=? AND EXISTS(SELECT 1 FROM school_invitations WHERE id=? AND token_hash=? AND accepted_at=?)").bind(marker,i.user_id,i.tenant_id,i.id,consumptionHash,marker),
    database.prepare("UPDATE auth_sessions SET revoked_at=?,revoke_reason='invitation_acceptance' WHERE user_id=? AND revoked_at IS NULL AND EXISTS(SELECT 1 FROM school_invitations WHERE id=? AND token_hash=? AND accepted_at=?)").bind(marker,i.user_id,i.id,consumptionHash,marker),
    database.prepare("INSERT INTO audit_events(id,tenant_id,actor_id,action,resource_type,reason,ip_hash,metadata_json,occurred_at) SELECT ?,?,?, 'auth.invitation.accept','authentication','success',?,?,? WHERE EXISTS(SELECT 1 FROM school_invitations WHERE id=? AND token_hash=? AND accepted_at=?)").bind(crypto.randomUUID(),i.tenant_id,i.user_id,metadata.ipHash,JSON.stringify({userAgentHash:metadata.userAgentHash}),marker,i.id,consumptionHash,marker),
  ]);
  return Number(result[0]?.meta?.changes??0)===1?i.user_id:null;
}
export async function writeSecurityEvent(input:{tenantId?:string|null;actorId?:string|null;action:string;outcome:"success"|"failure";ipHash?:string|null;metadata?:Record<string,unknown>}){await database.prepare("INSERT INTO audit_events(id,tenant_id,actor_id,action,resource_type,reason,ip_hash,metadata_json,occurred_at) VALUES(?,?,?,?, 'authentication',?,?,?,?)").bind(crypto.randomUUID(),input.tenantId??null,input.actorId??null,input.action,input.outcome,input.ipHash??null,JSON.stringify(input.metadata??{}),now()).run();}
export async function bootstrapPlatformAdmin(input:{email:string;fullName:string;passwordHash:string}){const id=crypto.randomUUID(),t=now();const result=await database.batch([database.prepare("INSERT INTO users(id,email,full_name,status,mfa_enabled,created_at,updated_at) SELECT ?,?,?,'active',0,?,? WHERE NOT EXISTS(SELECT 1 FROM platform_role_assignments)").bind(id,input.email,input.fullName,t,t),database.prepare("INSERT INTO auth_credentials(user_id,password_hash,credential_version,must_change_password,password_changed_at,created_at,updated_at) SELECT ?,?,1,0,?,?,? WHERE EXISTS(SELECT 1 FROM users WHERE id=?) AND NOT EXISTS(SELECT 1 FROM platform_role_assignments)").bind(id,input.passwordHash,t,t,t,id),database.prepare("INSERT INTO platform_role_assignments(user_id,role_key,created_at) SELECT ?,'platform_admin',? WHERE EXISTS(SELECT 1 FROM auth_credentials WHERE user_id=?) AND NOT EXISTS(SELECT 1 FROM platform_role_assignments)").bind(id,t,id)]);if(Number(result[2]?.meta?.changes??0)!==1)throw new Error("Platform administrator already exists");}
