"use client";

import { FormEvent, useState } from "react";
import { buildAssetReportPdf } from "./asset-report-pdf";
import styles from "./school.module.css";

type Category={id:string;name:string;code:string;method:string;life:number;salvagePct:number;rate:number;description:string;active:boolean};
type Asset={id:string;tag:string;name:string;category:string;brand:string;model:string;serial:string;quantity:number;status:string;condition:string;location:string;supplier:string;funding:string;purchaseDate:string;purchaseCost:number;invoice:string;method:string;depreciationStart:string;life:number;salvage:number;rate:number;warrantyProvider:string;warrantyExpiry:string;insured:boolean;insuranceProvider:string;policy:string;insuranceExpiry:string;notes:string};
type Assignment={id:string;assetId:string;asset:string;holderType:string;holder:string;assigned:string;expected:string;condition:string;returned:string;status:string;remarks:string};
type Maintenance={id:string;assetId:string;asset:string;title:string;type:string;frequency:string;nextDue:string;assigned:string;vendor:string;estimated:number;status:string;reported:string;completed:string;cost:number;description:string};
type Disposal={id:string;assetId:string;asset:string;method:string;date:string;realised:number;bookValue:number;recipient:string;reason:string;status:string;requested:string};
type Audit={id:string;title:string;scope:string;assets:number;verified:number;missing:number;conditionIssues:number;status:string;by:string;started:string};

const routes=["Asset Dashboard","Asset Guide","Asset Register","Asset Categories","Asset Assignments","Asset Depreciation","Asset Maintenance","Asset Disposals","Asset Audits","Asset Reports"];
const categoriesSeed:Category[]=[
  {id:"cat-it",name:"IT Equipment",code:"IT",method:"Written Down Value",life:60,salvagePct:5,rate:20,description:"Computers, printers and networking equipment",active:true},
  {id:"cat-fur",name:"Furniture & Fixtures",code:"FUR",method:"Straight Line",life:120,salvagePct:5,rate:10,description:"Classroom and office furniture",active:true},
  {id:"cat-lab",name:"Lab Apparatus",code:"LAB",method:"Straight Line",life:84,salvagePct:5,rate:12,description:"Science laboratory equipment",active:true},
  {id:"cat-av",name:"AV Equipment",code:"AV",method:"Written Down Value",life:60,salvagePct:5,rate:20,description:"Projectors, smart boards and audio",active:true},
  {id:"cat-sport",name:"Sports Equipment",code:"SPT",method:"Straight Line",life:48,salvagePct:0,rate:25,description:"Indoor and outdoor sports equipment",active:true},
  {id:"cat-kit",name:"Kitchen Equipment",code:"KIT",method:"Straight Line",life:84,salvagePct:5,rate:12,description:"Canteen and kitchen appliances",active:true},
  {id:"cat-mus",name:"Musical Instruments",code:"MUS",method:"Straight Line",life:96,salvagePct:5,rate:12,description:"Music room instruments",active:true},
  {id:"cat-veh",name:"Vehicles",code:"VEH",method:"Written Down Value",life:120,salvagePct:10,rate:15,description:"School buses and service vehicles",active:true},
];
const assetsSeed:Asset[]=[
  {id:"a1",tag:"HIG-IT-001",name:"Lenovo ThinkCentre",category:"IT Equipment",brand:"Lenovo",model:"M80s",serial:"PC-260018",quantity:6,status:"In Use",condition:"Good",location:"Computer Lab",supplier:"Digital India Systems",funding:"School Fund",purchaseDate:"2024-04-10",purchaseCost:330000,invoice:"DIS/2404/118",method:"Written Down Value",depreciationStart:"2024-04-10",life:60,salvage:16500,rate:20,warrantyProvider:"Lenovo India",warrantyExpiry:"2027-04-09",insured:true,insuranceProvider:"ICICI Lombard",policy:"HIG/IT/2026",insuranceExpiry:"2027-03-31",notes:"Six desktop systems"},
  {id:"a2",tag:"HIG-SPT-001",name:"Cricket Kit",category:"Sports Equipment",brand:"SG",model:"Club Set",serial:"-",quantity:4,status:"In Store",condition:"Good",location:"Sports Store",supplier:"Champion Sports",funding:"School Fund",purchaseDate:"2025-06-12",purchaseCost:48000,invoice:"CS/994",method:"Straight Line",depreciationStart:"2025-06-12",life:48,salvage:0,rate:25,warrantyProvider:"",warrantyExpiry:"",insured:false,insuranceProvider:"",policy:"",insuranceExpiry:"",notes:""},
  {id:"a3",tag:"HIG-LAB-001",name:"Digital Balance",category:"Lab Apparatus",brand:"Wensar",model:"PGB 200",serial:"DB-4471",quantity:3,status:"In Use",condition:"Good",location:"Chemistry Lab",supplier:"Labline Instruments",funding:"Gov Grant",purchaseDate:"2024-07-02",purchaseCost:72000,invoice:"LI/4471",method:"Straight Line",depreciationStart:"2024-07-02",life:84,salvage:3600,rate:12,warrantyProvider:"Wensar",warrantyExpiry:"2027-07-01",insured:false,insuranceProvider:"",policy:"",insuranceExpiry:"",notes:""},
  {id:"a4",tag:"HIG-KIT-001",name:"Water Purifier",category:"Kitchen Equipment",brand:"Kent",model:"Grand Plus",serial:"WP-8834",quantity:3,status:"In Use",condition:"Good",location:"Canteen",supplier:"Kent Dealer",funding:"CSR",purchaseDate:"2025-01-15",purchaseCost:57000,invoice:"KD/8834",method:"Straight Line",depreciationStart:"2025-01-15",life:84,salvage:2850,rate:12,warrantyProvider:"Kent",warrantyExpiry:"2027-01-14",insured:false,insuranceProvider:"",policy:"",insuranceExpiry:"",notes:""},
  {id:"a5",tag:"HIG-AV-001",name:"Wireless Microphone",category:"AV Equipment",brand:"Ahuja",model:"AWM-700U2",serial:"WM-1778",quantity:2,status:"In Store",condition:"Poor",location:"Auditorium Store",supplier:"Sound Planet",funding:"Donation",purchaseDate:"2022-08-08",purchaseCost:42000,invoice:"SP/778",method:"Written Down Value",depreciationStart:"2022-08-08",life:60,salvage:2100,rate:20,warrantyProvider:"",warrantyExpiry:"",insured:false,insuranceProvider:"",policy:"",insuranceExpiry:"",notes:"Disposal proposed"},
  {id:"a6",tag:"HIG-IT-002",name:"HP ProBook",category:"IT Equipment",brand:"HP",model:"440 G9",serial:"HP-99382",quantity:5,status:"In Use",condition:"Good",location:"Faculty Room",supplier:"Digital India Systems",funding:"School Fund",purchaseDate:"2024-11-22",purchaseCost:325000,invoice:"DIS/2411/88",method:"Written Down Value",depreciationStart:"2024-11-22",life:60,salvage:16250,rate:20,warrantyProvider:"HP India",warrantyExpiry:"2027-11-21",insured:true,insuranceProvider:"ICICI Lombard",policy:"HIG/IT/2026",insuranceExpiry:"2027-03-31",notes:""},
  {id:"a7",tag:"HIG-SPT-002",name:"Football Set",category:"Sports Equipment",brand:"Nivia",model:"Storm",serial:"-",quantity:4,status:"In Store",condition:"New",location:"Sports Store",supplier:"Champion Sports",funding:"School Fund",purchaseDate:"2026-06-15",purchaseCost:28000,invoice:"CS/1208",method:"Straight Line",depreciationStart:"2026-06-15",life:48,salvage:0,rate:25,warrantyProvider:"",warrantyExpiry:"",insured:false,insuranceProvider:"",policy:"",insuranceExpiry:"",notes:""},
  {id:"a8",tag:"HIG-FUR-001",name:"Principal Office Chair",category:"Furniture & Fixtures",brand:"Godrej",model:"Motion",serial:"GC-239",quantity:1,status:"In Use",condition:"Good",location:"Principal Office",supplier:"Godrej Interio",funding:"School Fund",purchaseDate:"2025-04-04",purchaseCost:32000,invoice:"GI/239",method:"Straight Line",depreciationStart:"2025-04-04",life:120,salvage:1600,rate:10,warrantyProvider:"Godrej",warrantyExpiry:"2028-04-03",insured:false,insuranceProvider:"",policy:"",insuranceExpiry:"",notes:""},
  {id:"a9",tag:"HIG-AV-002",name:"Epson Projector",category:"AV Equipment",brand:"Epson",model:"EB-E01",serial:"EP-77812",quantity:1,status:"Under Maintenance",condition:"Fair",location:"AV Room",supplier:"Vision Tech",funding:"School Fund",purchaseDate:"2023-05-18",purchaseCost:56000,invoice:"VT/7812",method:"Written Down Value",depreciationStart:"2023-05-18",life:60,salvage:2800,rate:20,warrantyProvider:"Epson",warrantyExpiry:"2026-08-17",insured:false,insuranceProvider:"",policy:"",insuranceExpiry:"",notes:"Lamp service"},
  {id:"a10",tag:"HIG-VEH-001",name:"School Bus",category:"Vehicles",brand:"Tata",model:"Starbus 40",serial:"MAT78214",quantity:1,status:"Under Maintenance",condition:"Good",location:"Transport Yard",supplier:"Tata Motors",funding:"School Fund",purchaseDate:"2021-04-01",purchaseCost:1770000,invoice:"TM/78214",method:"Written Down Value",depreciationStart:"2021-04-01",life:120,salvage:177000,rate:15,warrantyProvider:"Tata Motors",warrantyExpiry:"2024-03-31",insured:true,insuranceProvider:"New India Assurance",policy:"NIA/BUS/2026",insuranceExpiry:"2027-03-31",notes:""},
  {id:"a11",tag:"HIG-AV-003",name:"BenQ Smart Board",category:"AV Equipment",brand:"BenQ",model:"RM7503",serial:"BQ-7591",quantity:1,status:"Under Maintenance",condition:"Good",location:"Grade 10 A",supplier:"Vision Tech",funding:"CSR",purchaseDate:"2025-03-10",purchaseCost:285000,invoice:"VT/7591",method:"Written Down Value",depreciationStart:"2025-03-10",life:60,salvage:14250,rate:20,warrantyProvider:"BenQ",warrantyExpiry:"2028-03-09",insured:false,insuranceProvider:"",policy:"",insuranceExpiry:"",notes:""},
  {id:"a12",tag:"HIG-LAB-002",name:"Compound Microscope",category:"Lab Apparatus",brand:"Magnus",model:"MLX-B",serial:"MX-9021",quantity:1,status:"Under Maintenance",condition:"Fair",location:"Biology Lab",supplier:"Labline Instruments",funding:"Gov Grant",purchaseDate:"2023-07-12",purchaseCost:39100,invoice:"LI/9021",method:"Straight Line",depreciationStart:"2023-07-12",life:84,salvage:1955,rate:12,warrantyProvider:"Magnus",warrantyExpiry:"2026-07-11",insured:false,insuranceProvider:"",policy:"",insuranceExpiry:"",notes:"Calibration due"},
];
const assignmentSeed:Assignment[]=[
  {id:"as1",assetId:"a1",asset:"Lenovo ThinkCentre",holderType:"Department",holder:"Computer Lab",assigned:"2026-04-01",expected:"2027-03-31",condition:"Good",returned:"",status:"Active",remarks:"Lab allocation"},
  {id:"as2",assetId:"a6",asset:"HP ProBook",holderType:"Staff",holder:"Riya Kapoor (Teacher)",assigned:"2026-04-03",expected:"2027-03-31",condition:"Good",returned:"",status:"Active",remarks:"Faculty use"},
  {id:"as3",assetId:"a8",asset:"Principal Office Chair",holderType:"Department",holder:"Principal Office",assigned:"2025-04-05",expected:"",condition:"Good",returned:"",status:"Active",remarks:"Permanent allocation"},
];
const maintenanceSeed:Maintenance[]=[
  {id:"m1",assetId:"a9",asset:"Epson Projector",title:"Lamp and filter service",type:"Corrective",frequency:"One time",nextDue:"2026-07-18",assigned:"Facilities Team",vendor:"Vision Tech",estimated:6500,status:"Overdue",reported:"2026-07-12",completed:"",cost:0,description:"Low brightness and filter warning"},
  {id:"m2",assetId:"a10",asset:"School Bus",title:"Quarterly vehicle service",type:"Preventive",frequency:"Quarterly",nextDue:"2026-07-20",assigned:"Transport Manager",vendor:"Tata Motors",estimated:18000,status:"Overdue",reported:"2026-07-15",completed:"",cost:0,description:"Scheduled engine and brake service"},
  {id:"m3",assetId:"a11",asset:"BenQ Smart Board",title:"Touch alignment inspection",type:"Inspection",frequency:"Half-yearly",nextDue:"2026-07-30",assigned:"IT Team",vendor:"Vision Tech",estimated:2500,status:"Due Soon",reported:"2026-07-20",completed:"",cost:0,description:"Intermittent touch offset"},
  {id:"m4",assetId:"a12",asset:"Compound Microscope",title:"Annual calibration",type:"Calibration",frequency:"Annual",nextDue:"2026-07-25",assigned:"Lab Assistant",vendor:"Labline Instruments",estimated:3200,status:"Due Soon",reported:"2026-07-18",completed:"",cost:0,description:"Calibration certificate renewal"},
];
const disposalSeed:Disposal[]=[{id:"d1",assetId:"a5",asset:"Wireless Microphone",method:"Written Off",date:"2026-07-22",realised:0,bookValue:8600,recipient:"",reason:"Repair cost exceeds current value",status:"Pending Approval",requested:"Ankit Yadav"}];
const auditSeed:Audit[]=[
  {id:"au1",title:"Computer Lab Spot-check",scope:"By location · Computer Lab",assets:2,verified:1,missing:0,conditionIssues:0,status:"Open",by:"Ankit Yadav",started:"2026-07-22"},
  {id:"au2",title:"Annual Physical Verification 2025–26",scope:"All assets",assets:29,verified:29,missing:0,conditionIssues:2,status:"Completed",by:"Priya Sharma",started:"2026-03-20"},
];

const money=(n:number)=>`₹${Math.round(n).toLocaleString("en-IN")}`;
const isoToday=()=>new Date().toISOString().slice(0,10);
const yearsOwned=(asset:Asset)=>Math.max(0,(Date.now()-new Date(asset.depreciationStart||asset.purchaseDate).getTime())/31557600000);
function bookValue(asset:Asset){const years=yearsOwned(asset);if(asset.method==="No Depreciation")return asset.purchaseCost;if(asset.method==="Straight Line")return Math.max(asset.salvage,asset.purchaseCost-(asset.purchaseCost-asset.salvage)*Math.min(years,asset.life/12)/(asset.life/12));return Math.max(asset.salvage,asset.purchaseCost*Math.pow(1-asset.rate/100,years));}
function uid(prefix:string){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;}

export function AssetManagementReferencePage({page,onPage}:{page:string;onPage:(page:string)=>void}){
  const [assets,setAssets]=useState(assetsSeed),[categories,setCategories]=useState(categoriesSeed),[assignments,setAssignments]=useState(assignmentSeed),[maintenance,setMaintenance]=useState(maintenanceSeed),[disposals,setDisposals]=useState(disposalSeed),[audits,setAudits]=useState(auditSeed),[selected,setSelected]=useState("a1"),[toast,setToast]=useState("");
  function notify(message:string){setToast(message);globalThis.setTimeout(()=>setToast(""),2400);}
  const common={assets,categories,onPage,notify,setAssets};
  let body;
  if(page==="Asset Guide")body=<AssetGuide onPage={onPage}/>;
  else if(page==="Asset Register")body=<AssetRegister {...common} onSelect={(id)=>{setSelected(id);onPage("Asset Details");}}/>;
  else if(page==="Register Asset")body=<AssetForm {...common}/>;
  else if(page==="Asset Details")body=<AssetDetails asset={assets.find(x=>x.id===selected)??assets[0]} onPage={onPage}/>;
  else if(page==="Print Asset Tags")body=<AssetTags assets={assets}/>;
  else if(page==="Asset Categories")body=<AssetCategories categories={categories} setCategories={setCategories} notify={notify}/>;
  else if(page==="Asset Assignments")body=<AssetAssignments assets={assets} assignments={assignments} setAssignments={setAssignments} setAssets={setAssets} notify={notify}/>;
  else if(page==="Asset Depreciation")body=<AssetDepreciation assets={assets} notify={notify}/>;
  else if(page==="Asset Maintenance")body=<AssetMaintenancePage assets={assets} maintenance={maintenance} setMaintenance={setMaintenance} setAssets={setAssets} notify={notify}/>;
  else if(page==="Asset Disposals")body=<AssetDisposalsPage assets={assets} disposals={disposals} setDisposals={setDisposals} setAssets={setAssets} notify={notify}/>;
  else if(page==="Asset Audits")body=<AssetAudits audits={audits} setAudits={setAudits} onPage={onPage} notify={notify}/>;
  else if(page==="New Asset Audit")body=<AssetAuditForm assets={assets} setAudits={setAudits} onPage={onPage} notify={notify}/>;
  else if(page==="Asset Reports")body=<AssetReports assets={assets} assignments={assignments} maintenance={maintenance} disposals={disposals} onPage={onPage} notify={notify}/>;
  else if(page.endsWith("Report"))body=<AssetReportDetail page={page} assets={assets} assignments={assignments} maintenance={maintenance} disposals={disposals} onPage={onPage} notify={notify}/>;
  else body=<AssetDashboard assets={assets} categories={categories} maintenance={maintenance} onPage={onPage}/>;
  return <><AssetHeader page={page} onPage={onPage}/>{body}{toast&&<div className={styles.assetToast}>✓ {toast}</div>}</>;
}

function AssetHeader({page,onPage}:{page:string;onPage:(page:string)=>void}){return <><header className={styles.assetHeader}><div><span>OPERATIONS · ASSET LIFECYCLE</span><h1>{page==="Asset Dashboard"?"Asset Management":page}</h1><p>Register, allocate, maintain, depreciate and verify every school asset.</p></div>{page==="Asset Register"?<div><button onClick={()=>onPage("Print Asset Tags")}>▦ Print Tags</button><button onClick={()=>onPage("Register Asset")}>＋ Register Asset</button></div>:page==="Asset Dashboard"?<button onClick={()=>onPage("Register Asset")}>＋ Register Asset</button>:null}</header><nav className={styles.assetTabs}>{routes.map(x=><button className={page===x||(x==="Asset Reports"&&page.endsWith("Report"))?styles.assetTabActive:""} onClick={()=>onPage(x)} key={x}>{x.replace("Asset ","")}</button>)}</nav></>;}
function APanel({title,subtitle,children,action,onAction}:{title:string;subtitle?:string;children:React.ReactNode;action?:string;onAction?:()=>void}){return <article className={styles.assetPanel}><header><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action&&<button onClick={onAction}>{action}</button>}</header>{children}</article>;}
function Badge({value}:{value:string}){return <em className={`${styles.assetBadge} ${value.includes("Overdue")||value.includes("Poor")||value.includes("Pending")?styles.assetDanger:value.includes("Active")||value.includes("Good")||value.includes("Completed")||value.includes("In Use")?styles.assetSuccess:""}`}>{value}</em>;}

function AssetDashboard({assets,categories,maintenance,onPage}:{assets:Asset[];categories:Category[];maintenance:Maintenance[];onPage:(p:string)=>void}){
  const purchase=assets.reduce((n,x)=>n+x.purchaseCost,0),book=assets.reduce((n,x)=>n+bookValue(x),0);
  return <><section className={styles.assetStats}>{[["AS","Total Assets",String(assets.reduce((n,x)=>n+x.quantity,0)),"Registered items"],["₹","Purchase Value",money(purchase),"All acquisitions"],["BV","Book Value",money(book),"After depreciation"],["!","Alerts",String(maintenance.filter(x=>x.status!=="Completed").length),"Maintenance attention"]].map(([icon,label,value,note])=><article key={label}><i>{icon}</i><div><span>{label}</span><b>{value}</b><small>{note}</small></div></article>)}</section><section className={styles.assetDashboardGrid}><APanel title="Maintenance Due & Overdue" subtitle="Priority work orders" action="View all" onAction={()=>onPage("Asset Maintenance")}><div className={styles.assetActivity}>{maintenance.map(x=><button onClick={()=>onPage("Asset Maintenance")} key={x.id}><i>⚙</i><span><b>{x.asset}</b><small>{x.title} · Due {x.nextDue}</small></span><Badge value={x.status}/></button>)}</div></APanel><APanel title="By Status" subtitle="Current asset distribution"><div className={styles.assetBars}>{["In Use","In Store","Under Maintenance","Disposed"].map(status=>{const count=assets.filter(x=>x.status===status).reduce((n,x)=>n+x.quantity,0);return <div key={status}><span>{status}</span><i><b style={{width:`${Math.max(5,count/32*100)}%`}}/></i><strong>{count}</strong></div>})}</div></APanel><APanel title="Assets by Category" subtitle="Inventory composition"><div className={styles.assetCategoryCloud}>{categories.map((category,index)=><button onClick={()=>onPage("Asset Register")} key={category.id}><i>{category.code}</i><span>{category.name}</span><b>{assets.filter(x=>x.category===category.name).reduce((n,x)=>n+x.quantity,0)}</b><small>{["#2d8aa0","#7057a0","#e09a25","#4977ae"][index%4]}</small></button>)}</div></APanel><APanel title="Warranty Expiring (next 30 days)" subtitle="Warranty attention window"><div className={styles.assetActivity}>{assets.filter(x=>x.warrantyExpiry&&x.warrantyExpiry<"2026-08-27").map(x=><button key={x.id}><i>W</i><span><b>{x.name}</b><small>{x.warrantyProvider||"Provider not recorded"}</small></span><Badge value={x.warrantyExpiry}/></button>)}</div></APanel><APanel title="Recently Registered" subtitle="Latest assets"><div className={styles.assetRecent}>{assets.slice(0,8).map(x=><button onClick={()=>onPage("Asset Register")} key={x.id}><i>{x.category.slice(0,2).toUpperCase()}</i><span><b>{x.name}</b><small>{x.tag} · {x.location}</small></span><Badge value={x.status}/></button>)}</div></APanel><APanel title="Recent Activity" subtitle="Lifecycle events"><div className={styles.assetTimeline}>{["School Bus maintenance work order created","HP ProBook allocated to Riya Kapoor","Computer Lab spot-check started","Wireless Microphone disposal requested"].map((x,i)=><p key={x}><i>{i+1}</i><span><b>{x}</b><small>{i+1} day{i?"s":""} ago · Ankit Yadav</small></span></p>)}</div></APanel></section></>;
}

function AssetGuide({onPage}:{onPage:(p:string)=>void}){return <><section className={styles.assetGuideHero}><span>ASSET OPERATIONS HANDBOOK</span><h2>Asset Lifecycle Step by Step</h2><p>A controlled workflow from procurement to retirement, with full custody and value history.</p></section><section className={styles.assetGuideFlow}>{[["01","Register","Capture identity, cost, supplier, documents and warranty.","Register Asset"],["02","Tag & Allocate","Print a tag and issue the item to a staff member or location.","Asset Assignments"],["03","Maintain","Schedule preventive work and record repair costs.","Asset Maintenance"],["04","Depreciate","Post periodic depreciation for accurate book value.","Asset Depreciation"],["05","Verify","Run physical audits and resolve variances.","Asset Audits"],["06","Dispose","Request and approve retirement with gain/loss.","Asset Disposals"]].map(([n,t,d,p])=><button onClick={()=>onPage(p)} key={n}><i>{n}</i><b>{t}</b><span>{d}</span><em>Open workflow →</em></button>)}</section><section className={styles.assetGuideGrid}><APanel title="Asset Statuses"><div className={styles.assetGuideList}>{[["In Store","Available for allocation"],["In Use","Allocated to a custodian or location"],["Under Maintenance","Temporarily unavailable"],["Retired","No longer operational"],["Disposed","Approved and closed"],["Lost","Missing after verification"]].map(([a,b])=><p key={a}><Badge value={a}/><span>{b}</span></p>)}</div></APanel><APanel title="Good to Know"><div className={styles.assetTips}><p><b>Asset tags are permanent.</b><span>Use the generated code on labels, invoices and audit sheets.</span></p><p><b>Approval protects the register.</b><span>A disposal request does not change asset status until approved.</span></p><p><b>Book value is calculated live.</b><span>Method, useful life and salvage value drive depreciation.</span></p></div></APanel><APanel title="Who Can Do What"><div className={styles.assetGuideList}>{[["School Admin","All asset operations and approvals"],["Accountant","Purchase value, depreciation and disposal review"],["Store Keeper","Register, allocate, return and tag"],["Auditor","Physical verification and reports"]].map(([a,b])=><p key={a}><b>{a}</b><span>{b}</span></p>)}</div></APanel><APanel title="Quick FAQ"><div className={styles.assetTips}><p><b>Can an allocated asset be disposed?</b><span>Return it first, then request disposal.</span></p><p><b>Can I import old assets?</b><span>Use the register export format as your import template.</span></p><p><b>Does maintenance affect book value?</b><span>Maintenance cost is reported separately unless capitalised.</span></p></div></APanel></section></>;}

function AssetRegister({assets,categories,onPage,onSelect}:{assets:Asset[];categories:Category[];onPage:(p:string)=>void;onSelect:(id:string)=>void;notify:(s:string)=>void;setAssets:React.Dispatch<React.SetStateAction<Asset[]>>}){
  const [search,setSearch]=useState(""),[category,setCategory]=useState(""),[status,setStatus]=useState("");
  const rows=assets.filter(x=>(!search||`${x.tag} ${x.name} ${x.serial}`.toLowerCase().includes(search.toLowerCase()))&&(!category||x.category===category)&&(!status||x.status===status));
  return <APanel title="Asset Register" subtitle={`${rows.length} registered records`}><div className={styles.assetFilters}><label>⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, tag or serial..."/></label><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All Categories</option>{categories.map(x=><option key={x.id}>{x.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Statuses</option>{["In Store","In Use","Under Maintenance","Retired","Disposed","Lost"].map(x=><option key={x}>{x}</option>)}</select><span/><button onClick={()=>onPage("Print Asset Tags")}>Print Tags</button><button onClick={()=>onPage("Register Asset")}>＋ Register Asset</button></div><div className={styles.assetTable}><div><b>Tag</b><b>Asset</b><b>Category</b><b>Status</b><b>Condition</b><b>Location</b><b>Book Value</b><b>Actions</b></div>{rows.map(x=><div key={x.id}><code>{x.tag}</code><p><b>{x.name}</b><small>{x.brand} {x.model} · Qty {x.quantity}</small></p><span>{x.category}</span><Badge value={x.status}/><Badge value={x.condition}/><span>{x.location}</span><strong>{money(bookValue(x))}</strong><span><button onClick={()=>onSelect(x.id)}>View</button><button>⋮</button></span></div>)}</div><footer className={styles.assetTableFoot}>Showing {rows.length} of {assets.length} records <span>Previous　<b>1</b>　Next</span></footer></APanel>;
}

function AssetForm({assets,categories,setAssets,onPage,notify}:{assets:Asset[];categories:Category[];setAssets:React.Dispatch<React.SetStateAction<Asset[]>>;onPage:(p:string)=>void;notify:(s:string)=>void}){
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),category=String(f.get("category")),cat=categories.find(x=>x.name===category);const asset:Asset={id:uid("asset"),tag:`HIG-${cat?.code??"AST"}-${String(assets.length+1).padStart(3,"0")}`,name:String(f.get("name")),category,brand:String(f.get("brand")),model:String(f.get("model")),serial:String(f.get("serial")),quantity:Number(f.get("quantity"))||1,status:String(f.get("status")),condition:String(f.get("condition")),location:String(f.get("location")),supplier:String(f.get("supplier")),funding:String(f.get("funding")),purchaseDate:String(f.get("purchaseDate")),purchaseCost:Number(f.get("purchaseCost"))||0,invoice:String(f.get("invoice")),method:String(f.get("method")),depreciationStart:String(f.get("depreciationStart")),life:Number(f.get("life"))||60,salvage:Number(f.get("salvage"))||0,rate:Number(f.get("rate"))||0,warrantyProvider:String(f.get("warrantyProvider")),warrantyExpiry:String(f.get("warrantyExpiry")),insured:f.get("insured")==="on",insuranceProvider:String(f.get("insuranceProvider")),policy:String(f.get("policy")),insuranceExpiry:String(f.get("insuranceExpiry")),notes:String(f.get("notes"))};setAssets(v=>[asset,...v]);notify(`${asset.name} registered as ${asset.tag}`);onPage("Asset Register");}
  return <form onSubmit={submit} className={styles.assetFormPage}><button type="button" onClick={()=>onPage("Asset Register")}>← Back to Asset Register</button><APanel title="Asset Identity" subtitle="Core identification and classification"><div className={styles.assetFormGrid}><Field name="name" label="Asset Name *" required/><Field name="tag" label="Asset Tag" placeholder="Generated automatically" disabled/><Select name="category" label="Category *" options={categories.map(x=>x.name)} required/><Field name="brand" label="Brand"/><Field name="model" label="Model Number"/><Field name="serial" label="Serial Number"/><Field name="quantity" label="Quantity *" type="number" defaultValue="1" required/><label className={styles.assetWide}>Description<textarea name="notes"/></label></div></APanel><APanel title="Status & Location" subtitle="Availability, condition and acquisition"><div className={styles.assetFormGrid}><Select name="status" label="Status" options={["In Store","In Use","Under Maintenance","Retired","Lost"]}/><Select name="condition" label="Condition" options={["New","Good","Fair","Poor","Damaged"]}/><Field name="location" label="Physical Location *" required/><Field name="supplier" label="Supplier"/><Select name="funding" label="Funding Source" options={["School Fund","Gov Grant","Donation","CSR","Other"]}/><Field name="purchaseDate" label="Purchase Date" type="date"/><Field name="purchaseCost" label="Purchase Cost (₹)" type="number"/><Field name="invoice" label="Invoice Number"/></div></APanel><APanel title="Depreciation" subtitle="Book value calculation"><div className={styles.assetFormGrid}><Select name="method" label="Method" options={["No Depreciation","Straight Line","Written Down Value","Declining Balance"]}/><Field name="depreciationStart" label="Start Date" type="date"/><Field name="life" label="Useful Life (months)" type="number" defaultValue="60"/><Field name="salvage" label="Salvage Value (₹)" type="number" defaultValue="0"/><Field name="rate" label="Rate (% / year)" type="number" defaultValue="20"/><Field name="openingValue" label="Opening Book Value (₹)" type="number"/></div></APanel><APanel title="Warranty, Insurance & Media"><div className={styles.assetFormGrid}><Field name="warrantyProvider" label="Warranty Provider"/><Field name="warrantyExpiry" label="Warranty Expiry" type="date"/><label className={styles.assetCheck}><input name="insured" type="checkbox"/><span>Asset is insured</span></label><Field name="insuranceProvider" label="Insurance Provider"/><Field name="policy" label="Policy Number"/><Field name="insuranceExpiry" label="Insurance Expiry" type="date"/><Field name="photo" label="Asset Photo" type="file"/><Field name="warrantyDoc" label="Warranty Document" type="file"/><Field name="purchaseDoc" label="Purchase Document" type="file"/></div></APanel><div className={styles.assetFormActions}><button type="button" onClick={()=>onPage("Asset Register")}>Cancel</button><button>Register Asset</button></div></form>;
}
function Field({label,name,type="text",defaultValue,placeholder,required,disabled}:{label:string;name:string;type?:string;defaultValue?:string;placeholder?:string;required?:boolean;disabled?:boolean}){return <label>{label}<input name={name} type={type} defaultValue={defaultValue} placeholder={placeholder} required={required} disabled={disabled}/></label>;}
function Select({label,name,options,required}:{label:string;name:string;options:string[];required?:boolean}){return <label>{label}<select name={name} required={required}>{options.map(x=><option key={x}>{x}</option>)}</select></label>;}

function AssetDetails({asset,onPage}:{asset:Asset;onPage:(p:string)=>void}){return <><button className={styles.assetBack} onClick={()=>onPage("Asset Register")}>← Back to Asset Register</button><section className={styles.assetDetailHero}><i>{asset.category.slice(0,2).toUpperCase()}</i><div><code>{asset.tag}</code><h2>{asset.name}</h2><p>{asset.brand} {asset.model} · Serial {asset.serial}</p></div><Badge value={asset.status}/><button onClick={()=>globalThis.print()}>Print Tag</button></section><section className={styles.assetDetailGrid}><APanel title="Asset Information"><dl>{[["Category",asset.category],["Quantity",String(asset.quantity)],["Condition",asset.condition],["Location",asset.location],["Supplier",asset.supplier],["Funding Source",asset.funding],["Purchase Date",asset.purchaseDate],["Invoice",asset.invoice]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b||"—"}</dd></div>)}</dl></APanel><APanel title="Financial Value"><dl>{[["Purchase Cost",money(asset.purchaseCost)],["Book Value",money(bookValue(asset))],["Method",asset.method],["Rate",`${asset.rate}% per year`],["Useful Life",`${asset.life} months`],["Salvage Value",money(asset.salvage)]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></APanel><APanel title="Warranty & Insurance"><dl>{[["Warranty Provider",asset.warrantyProvider],["Warranty Expiry",asset.warrantyExpiry],["Insured",asset.insured?"Yes":"No"],["Insurance Provider",asset.insuranceProvider],["Policy Number",asset.policy],["Insurance Expiry",asset.insuranceExpiry]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b||"—"}</dd></div>)}</dl></APanel><APanel title="Movement Timeline"><div className={styles.assetTimeline}>{["Asset registered","Purchase information verified",asset.status==="In Use"?"Allocated to custodian":"Moved to current location"].map((x,i)=><p key={x}><i>✓</i><span><b>{x}</b><small>{i?asset.purchaseDate:asset.depreciationStart}</small></span></p>)}</div></APanel></section></>;}
function AssetTags({assets}:{assets:Asset[]}){return <><div className={styles.assetPrintBar}><div><h2>Print Asset Tags</h2><p>Select records, then print QR-ready labels.</p></div><button onClick={()=>globalThis.print()}>▦ Print Selected</button></div><section className={styles.assetTags}>{assets.slice(0,12).map(x=><label key={x.id}><input type="checkbox" defaultChecked/><article><i>▦</i><div><b>{x.tag}</b><span>{x.name}</span><small>Hig School · {x.location}</small></div></article></label>)}</section></>;}

function AssetCategories({categories,setCategories,notify}:{categories:Category[];setCategories:React.Dispatch<React.SetStateAction<Category[]>>;notify:(s:string)=>void}){
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get("name"));setCategories(v=>[...v,{id:uid("cat"),name,code:String(f.get("code")),method:String(f.get("method")),life:Number(f.get("life")),salvagePct:Number(f.get("salvage")),rate:Number(f.get("rate")),description:String(f.get("description")),active:true}]);e.currentTarget.reset();notify(`${name} category added`);}
  return <section className={styles.assetSplit}><form onSubmit={submit} className={styles.assetPanel}><header><div><h2>Add Asset Category</h2><p>Set default valuation rules.</p></div></header><div className={styles.assetStack}><Field name="name" label="Name *" required/><Field name="code" label="Code *" required/><Select name="method" label="Default Depreciation Method" options={["Straight Line","Written Down Value","No Depreciation"]}/><Field name="life" label="Useful Life (months)" type="number" defaultValue="60"/><Field name="salvage" label="Salvage (%)" type="number" defaultValue="5"/><Field name="rate" label="Rate (% / year)" type="number" defaultValue="20"/><label>Description<textarea name="description"/></label><label className={styles.assetCheck}><input type="checkbox" defaultChecked/><span>Active</span></label><button>Add Category</button></div></form><APanel title="Asset Categories" subtitle={`${categories.length} configured`}><div className={styles.assetCategoryTable}><div><b>Category</b><b>Method</b><b>Life</b><b>Rate</b><b>Status</b><b>Actions</b></div>{categories.map(x=><div key={x.id}><p><i>{x.code}</i><span><b>{x.name}</b><small>{x.description}</small></span></p><span>{x.method}</span><span>{x.life} months</span><span>{x.rate}%</span><Badge value={x.active?"Active":"Inactive"}/><span><button>Edit</button><button onClick={()=>{setCategories(v=>v.map(c=>c.id===x.id?{...c,active:!c.active}:c));notify(`${x.name} ${x.active?"disabled":"enabled"}`);}}>{x.active?"Disable":"Enable"}</button></span></div>)}</div></APanel></section>;
}

function AssetAssignments({assets,assignments,setAssignments,setAssets,notify}:{assets:Asset[];assignments:Assignment[];setAssignments:React.Dispatch<React.SetStateAction<Assignment[]>>;setAssets:React.Dispatch<React.SetStateAction<Asset[]>>;notify:(s:string)=>void}){
  const [open,setOpen]=useState(false),[returning,setReturning]=useState<Assignment|null>(null),[transfer,setTransfer]=useState<Assignment|null>(null);
  function allocate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),asset=assets.find(x=>x.id===f.get("assetId"));if(!asset)return;setAssignments(v=>[{id:uid("as"),assetId:asset.id,asset:asset.name,holderType:String(f.get("holderType")),holder:String(f.get("holder")),assigned:String(f.get("assigned")),expected:String(f.get("expected")),condition:String(f.get("condition")),returned:"",status:"Active",remarks:String(f.get("remarks"))},...v]);setAssets(v=>v.map(x=>x.id===asset.id?{...x,status:"In Use"}:x));setOpen(false);notify(`${asset.name} allocated`);}
  function doReturn(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!returning)return;const f=new FormData(e.currentTarget);setAssignments(v=>v.map(x=>x.id===returning.id?{...x,status:"Returned",returned:String(f.get("date")),condition:String(f.get("condition")),remarks:String(f.get("remarks"))}:x));setAssets(v=>v.map(x=>x.id===returning.assetId?{...x,status:"In Store",condition:String(f.get("condition"))}:x));setReturning(null);notify(`${returning.asset} returned to store`);}
  function doTransfer(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!transfer)return;const f=new FormData(e.currentTarget);setAssignments(v=>v.map(x=>x.id===transfer.id?{...x,holderType:String(f.get("holderType")),holder:String(f.get("holder")),expected:String(f.get("expected")),condition:String(f.get("condition")),remarks:String(f.get("remarks"))}:x));setTransfer(null);notify(`${transfer.asset} transferred`);}
  return <><div className={styles.assetActionLine}><div><h2>Asset Allocations</h2><p>Issue assets, transfer custody and record returns.</p></div><button onClick={()=>setOpen(true)}>＋ New Allocation</button></div><APanel title="Allocation Register" subtitle={`${assignments.filter(x=>x.status==="Active").length} active allocations`}><div className={styles.assetAssignmentTable}><div><b>Asset</b><b>Holder</b><b>Assigned</b><b>Expected Return</b><b>Status</b><b>Actions</b></div>{assignments.map(x=><div key={x.id}><p><b>{x.asset}</b><small>{assets.find(a=>a.id===x.assetId)?.tag}</small></p><p><b>{x.holder}</b><small>{x.holderType}</small></p><span>{x.assigned}</span><span>{x.expected||"Open-ended"}</span><Badge value={x.status}/><span>{x.status==="Active"&&<><button onClick={()=>setReturning(x)}>Return</button><button onClick={()=>setTransfer(x)}>Transfer</button></>}</span></div>)}</div></APanel>{open&&<Modal title="New Asset Allocation" close={()=>setOpen(false)}><form onSubmit={allocate} className={styles.assetModalForm}><Select name="assetId" label="Asset (In Store)" options={assets.filter(x=>x.status==="In Store").map(x=>x.id)}/><Select name="holderType" label="Assign To" options={["Staff","Department","Class / Room"]}/><Field name="holder" label="Holder / Location *" required/><Field name="assigned" label="Assigned Date *" type="date" defaultValue={isoToday()} required/><Field name="expected" label="Expected Return" type="date"/><Select name="condition" label="Condition at Issue" options={["New","Good","Fair","Poor"]}/><label>Remarks<textarea name="remarks"/></label><footer><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button>Allocate Asset</button></footer></form></Modal>}{returning&&<Modal title={`Return · ${returning.asset}`} close={()=>setReturning(null)}><form onSubmit={doReturn} className={styles.assetModalForm}><Field name="date" label="Return Date" type="date" defaultValue={isoToday()} required/><Select name="condition" label="Condition on Return" options={["Good","Fair","Poor","Damaged"]}/><label>Remarks<textarea name="remarks"/></label><footer><button type="button" onClick={()=>setReturning(null)}>Cancel</button><button>Confirm Return</button></footer></form></Modal>}{transfer&&<Modal title={`Transfer · ${transfer.asset}`} close={()=>setTransfer(null)}><form onSubmit={doTransfer} className={styles.assetModalForm}><Select name="holderType" label="New Holder Type" options={["Staff","Department","Class / Room"]}/><Field name="holder" label="New Holder *" required/><Field name="expected" label="Expected Return" type="date"/><Select name="condition" label="Condition" options={["Good","Fair","Poor"]}/><label>Remarks<textarea name="remarks"/></label><footer><button type="button" onClick={()=>setTransfer(null)}>Cancel</button><button>Transfer Asset</button></footer></form></Modal>}</>;
}

function AssetDepreciation({assets,notify}:{assets:Asset[];notify:(s:string)=>void}){
  const [fy,setFy]=useState("2026–27"),[posted,setPosted]=useState(false);
  return <><div className={styles.assetActionLine}><div><h2>Depreciation Register</h2><p>Preview and post depreciation for the selected financial year.</p></div><div><select value={fy} onChange={e=>setFy(e.target.value)}><option>2026–27</option><option>2025–26</option></select><button onClick={()=>{setPosted(true);notify(`Depreciation posted for ${fy}`);}}>Run Depreciation</button></div></div><section className={styles.assetDepSummary}>{[["Opening Value",money(assets.reduce((n,x)=>n+x.purchaseCost,0))],["Period Depreciation",money(assets.reduce((n,x)=>n+(x.purchaseCost-bookValue(x)),0))],["Accumulated",money(assets.reduce((n,x)=>n+(x.purchaseCost-bookValue(x)),0))],["Closing Book Value",money(assets.reduce((n,x)=>n+bookValue(x),0))]].map(([a,b])=><article key={a}><span>{a}</span><b>{b}</b><small>{posted?"Posted":"Preview"}</small></article>)}</section><APanel title="Depreciation Schedule" subtitle={`Financial year ${fy}`}><div className={styles.assetDepTable}><div><b>Asset</b><b>Period</b><b>FY</b><b>Method</b><b>Opening</b><b>Depreciation</b><b>Accumulated</b><b>Closing</b></div>{assets.map(x=>{const close=bookValue(x),dep=x.purchaseCost-close;return <div key={x.id}><p><b>{x.name}</b><small>{x.tag}</small></p><span>Apr–Mar</span><span>{fy}</span><span>{x.method}</span><strong>{money(x.purchaseCost)}</strong><strong>{money(dep)}</strong><strong>{money(dep)}</strong><strong>{money(close)}</strong></div>})}</div></APanel></>;
}

function AssetMaintenancePage({assets,maintenance,setMaintenance,setAssets,notify}:{assets:Asset[];maintenance:Maintenance[];setMaintenance:React.Dispatch<React.SetStateAction<Maintenance[]>>;setAssets:React.Dispatch<React.SetStateAction<Asset[]>>;notify:(s:string)=>void}){
  const [mode,setMode]=useState<"schedule"|"log"|null>(null);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),asset=assets.find(x=>x.id===f.get("assetId"));if(!asset)return;const title=String(f.get("title")||f.get("problem"));setMaintenance(v=>[{id:uid("m"),assetId:asset.id,asset:asset.name,title,type:String(f.get("type")),frequency:String(f.get("frequency")||"One time"),nextDue:String(f.get("nextDue")||isoToday()),assigned:String(f.get("assigned")),vendor:String(f.get("vendor")),estimated:Number(f.get("estimated")),status:mode==="schedule"?"Scheduled":"Open",reported:String(f.get("reported")||isoToday()),completed:"",cost:Number(f.get("cost")),description:String(f.get("description"))},...v]);if(mode==="log")setAssets(v=>v.map(x=>x.id===asset.id?{...x,status:"Under Maintenance"}:x));setMode(null);notify(`${mode==="schedule"?"Schedule":"Work log"} saved`);}
  function complete(item:Maintenance){const cost=globalThis.prompt("Final maintenance cost (₹)",String(item.estimated))??String(item.estimated);setMaintenance(v=>v.map(x=>x.id===item.id?{...x,status:"Completed",completed:isoToday(),cost:Number(cost)}:x));setAssets(v=>v.map(x=>x.id===item.assetId?{...x,status:"In Store",condition:"Good"}:x));notify(`${item.asset} maintenance completed`);}
  return <><div className={styles.assetActionLine}><div><h2>Asset Maintenance</h2><p>Plan preventive servicing and record completed work.</p></div><div><button onClick={()=>setMode("schedule")}>＋ Add Schedule</button><button onClick={()=>setMode("log")}>＋ Log Maintenance</button></div></div><section className={styles.assetMaintStats}>{["Overdue","Due Soon","Scheduled","Completed"].map(x=><article key={x}><span>{x}</span><b>{maintenance.filter(m=>m.status===x).length}</b></article>)}</section><APanel title="Maintenance Schedules" subtitle="Recurring and upcoming work"><div className={styles.assetMaintenanceTable}><div><b>Asset / Work</b><b>Type</b><b>Frequency</b><b>Next Due</b><b>Assigned / Vendor</b><b>Estimate</b><b>Status</b><b>Actions</b></div>{maintenance.map(x=><div key={x.id}><p><b>{x.asset}</b><small>{x.title}</small></p><span>{x.type}</span><span>{x.frequency}</span><span>{x.nextDue}</span><p><b>{x.assigned}</b><small>{x.vendor}</small></p><strong>{money(x.estimated)}</strong><Badge value={x.status}/><span>{x.status!=="Completed"&&<button onClick={()=>complete(x)}>Complete</button>}<button>View</button></span></div>)}</div></APanel>{mode&&<Modal title={mode==="schedule"?"Add Maintenance Schedule":"Log Maintenance Work"} close={()=>setMode(null)}><form onSubmit={submit} className={styles.assetModalForm}><Select name="assetId" label="Asset *" options={assets.map(x=>x.id)}/>{mode==="schedule"?<><Field name="title" label="Schedule Title *" required/><Select name="type" label="Type" options={["Preventive","Inspection","Calibration","Servicing"]}/><Select name="frequency" label="Frequency" options={["Monthly","Quarterly","Half-yearly","Annual","One time"]}/><Field name="nextDue" label="Next Due Date" type="date" required/><Field name="assigned" label="Assigned To"/><Field name="vendor" label="Vendor"/><Field name="estimated" label="Estimated Cost (₹)" type="number"/></>:<><Field name="problem" label="Problem / Work Title *" required/><Select name="type" label="Type" options={["Corrective","Preventive","Inspection","Calibration"]}/><Field name="reported" label="Reported Date" type="date" defaultValue={isoToday()}/><Field name="cost" label="Cost (₹)" type="number"/><Field name="assigned" label="Performed By"/><Field name="vendor" label="Vendor"/></>}<label>Action / Notes<textarea name="description"/></label><footer><button type="button" onClick={()=>setMode(null)}>Cancel</button><button>Save</button></footer></form></Modal>}</>;
}

function AssetDisposalsPage({assets,disposals,setDisposals,setAssets,notify}:{assets:Asset[];disposals:Disposal[];setDisposals:React.Dispatch<React.SetStateAction<Disposal[]>>;setAssets:React.Dispatch<React.SetStateAction<Asset[]>>;notify:(s:string)=>void}){
  const [open,setOpen]=useState(false);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),asset=assets.find(x=>x.id===f.get("assetId"));if(!asset)return;setDisposals(v=>[{id:uid("d"),assetId:asset.id,asset:asset.name,method:String(f.get("method")),date:String(f.get("date")),realised:Number(f.get("realised")),bookValue:bookValue(asset),recipient:String(f.get("recipient")),reason:String(f.get("reason")),status:"Pending Approval",requested:"Ankit Yadav"},...v]);setOpen(false);notify(`Disposal requested for ${asset.name}`);}
  function approve(x:Disposal){setDisposals(v=>v.map(d=>d.id===x.id?{...d,status:"Completed"}:d));setAssets(v=>v.map(a=>a.id===x.assetId?{...a,status:"Disposed"}:a));notify(`${x.asset} disposal approved`);}
  return <><div className={styles.assetActionLine}><div><h2>Asset Disposals</h2><p>Controlled retirement with approval and gain/loss tracking.</p></div><button onClick={()=>setOpen(true)}>＋ Request Disposal</button></div><APanel title="Disposal Register" subtitle={`${disposals.filter(x=>x.status==="Pending Approval").length} awaiting approval`}><div className={styles.assetDisposalTable}><div><b>Asset</b><b>Method</b><b>Date</b><b>Realised</b><b>Book Value</b><b>Gain / Loss</b><b>Status</b><b>Requested By</b><b>Actions</b></div>{disposals.map(x=><div key={x.id}><p><b>{x.asset}</b><small>{assets.find(a=>a.id===x.assetId)?.tag}</small></p><span>{x.method}</span><span>{x.date}</span><strong>{money(x.realised)}</strong><strong>{money(x.bookValue)}</strong><strong>{money(x.realised-x.bookValue)}</strong><Badge value={x.status}/><span>{x.requested}</span><span>{x.status==="Pending Approval"&&<button onClick={()=>approve(x)}>Approve</button>}<button>View</button></span></div>)}</div></APanel>{open&&<Modal title="Request Asset Disposal" close={()=>setOpen(false)}><form onSubmit={submit} className={styles.assetModalForm}><Select name="assetId" label="Asset *" options={assets.filter(x=>!["Disposed","In Use"].includes(x.status)).map(x=>x.id)}/><Select name="method" label="Disposal Method" options={["Sold","Scrapped","Donated","Written Off","Lost","Returned to Vendor","Traded In"]}/><Field name="date" label="Disposal Date" type="date" defaultValue={isoToday()}/><Field name="realised" label="Realised Value (₹)" type="number" defaultValue="0"/><Field name="recipient" label="Recipient / Buyer"/><label>Reason *<textarea name="reason" required/></label><Field name="document" label="Supporting Document" type="file"/><label>Remarks<textarea name="remarks"/></label><footer><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button>Submit for Approval</button></footer></form></Modal>}</>;
}

function AssetAudits({audits,setAudits,onPage,notify}:{audits:Audit[];setAudits:React.Dispatch<React.SetStateAction<Audit[]>>;onPage:(p:string)=>void;notify:(s:string)=>void}){
  function finish(x:Audit){setAudits(v=>v.map(a=>a.id===x.id?{...a,status:"Completed",verified:a.assets}:a));notify(`${x.title} completed`);}
  return <><div className={styles.assetActionLine}><div><h2>Physical Verification Sessions</h2><p>Count, inspect and reconcile the asset register.</p></div><button onClick={()=>onPage("New Asset Audit")}>＋ New Audit Session</button></div><section className={styles.assetAuditStats}>{[["Open",audits.filter(x=>x.status==="Open").length],["Assets to Verify",audits.filter(x=>x.status==="Open").reduce((n,x)=>n+x.assets-x.verified,0)],["Missing",audits.reduce((n,x)=>n+x.missing,0)],["Condition Issues",audits.reduce((n,x)=>n+x.conditionIssues,0)]].map(([a,b])=><article key={a}><span>{a}</span><b>{b}</b></article>)}</section><APanel title="Audit Sessions" subtitle={`${audits.length} verification records`}><div className={styles.assetAuditTable}><div><b>Title</b><b>Scope</b><b>Assets</b><b>Progress</b><b>Status</b><b>Started By</b><b>Started</b><b>Actions</b></div>{audits.map(x=><div key={x.id}><p><b>{x.title}</b><small>{x.missing} missing · {x.conditionIssues} issues</small></p><span>{x.scope}</span><strong>{x.assets}</strong><span><i><b style={{width:`${x.assets?x.verified/x.assets*100:0}%`}}/></i>{x.verified}/{x.assets}</span><Badge value={x.status}/><span>{x.by}</span><span>{x.started}</span><span>{x.status==="Open"?<button onClick={()=>finish(x)}>Verify & Complete</button>:<button>View</button>}</span></div>)}</div></APanel></>;
}
function AssetAuditForm({assets,setAudits,onPage,notify}:{assets:Asset[];setAudits:React.Dispatch<React.SetStateAction<Audit[]>>;onPage:(p:string)=>void;notify:(s:string)=>void}){
  const [scope,setScope]=useState("All assets");
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),filtered=scope==="By category"?assets.filter(x=>x.category===f.get("category")):scope==="By location"?assets.filter(x=>x.location===f.get("location")):assets;const title=String(f.get("title"));setAudits(v=>[{id:uid("au"),title,scope:scope==="All assets"?scope:`${scope} · ${f.get(scope==="By category"?"category":"location")}`,assets:filtered.length,verified:0,missing:0,conditionIssues:0,status:"Open",by:"Ankit Yadav",started:isoToday()},...v]);notify(`${title} started`);onPage("Asset Audits");}
  return <form onSubmit={submit} className={styles.assetAuditForm}><button type="button" onClick={()=>onPage("Asset Audits")}>← Back to Audits</button><APanel title="New Physical Verification Session" subtitle="Define the assets included in this count"><div className={styles.assetFormGrid}><Field name="title" label="Session Title *" required/><label>Scope<select value={scope} onChange={e=>setScope(e.target.value)}><option>All assets</option><option>By category</option><option>By location</option></select></label>{scope==="By category"&&<Select name="category" label="Category" options={[...new Set(assets.map(x=>x.category))]}/>} {scope==="By location"&&<Select name="location" label="Location" options={[...new Set(assets.map(x=>x.location))]}/>}<label className={styles.assetWide}>Notes<textarea name="notes"/></label></div></APanel><div className={styles.assetFormActions}><button type="button" onClick={()=>onPage("Asset Audits")}>Cancel</button><button>Start Verification</button></div></form>;
}

type ReportPage="Asset Register Report"|"Depreciation Register Report"|"Custody Report"|"Maintenance History Report"|"Warranty Expiry Report"|"Disposal Register Report"|"Movement Ledger Report";
type ReportData={title:string;description:string;headers:string[];rows:Array<Array<string|number>>;totalLabel:string;totalValue:string;filterIndex:number;filterLabel:string};
const reportPages:ReportPage[]=["Asset Register Report","Depreciation Register Report","Custody Report","Maintenance History Report","Warranty Expiry Report","Disposal Register Report","Movement Ledger Report"];
function reportData(page:ReportPage,assets:Asset[],assignments:Assignment[],maintenance:Maintenance[],disposals:Disposal[]):ReportData{
  if(page==="Asset Register Report")return {title:"Asset Register",description:"Full list of every fixed asset with status and value.",headers:["Tag","Name","Category","Status","Condition","Location","Purchase Date","Purchase Cost","Book Value"],rows:assets.map(x=>[x.tag,x.name,x.category,x.status,x.condition,x.location,x.purchaseDate,money(x.purchaseCost),money(bookValue(x))]),totalLabel:"Current book value",totalValue:money(assets.reduce((n,x)=>n+bookValue(x),0)),filterIndex:3,filterLabel:"Status"};
  if(page==="Depreciation Register Report")return {title:"Depreciation Register",description:"Every depreciation period with opening and closing value.",headers:["Asset","Tag","Method","Start Date","Useful Life","Opening Value","Accumulated Depreciation","Book Value"],rows:assets.map(x=>[x.name,x.tag,x.method,x.depreciationStart,`${x.life} months`,money(x.purchaseCost),money(x.purchaseCost-bookValue(x)),money(bookValue(x))]),totalLabel:"Accumulated depreciation",totalValue:money(assets.reduce((n,x)=>n+x.purchaseCost-bookValue(x),0)),filterIndex:2,filterLabel:"Method"};
  if(page==="Custody Report")return {title:"Custody / Allocation Register",description:"Who holds, or held, each asset.",headers:["Asset","Tag","Holder Type","Holder","Assigned","Expected Return","Returned","Condition","Status"],rows:assignments.map(x=>[x.asset,assets.find(a=>a.id===x.assetId)?.tag??"—",x.holderType,x.holder,x.assigned,x.expected||"Open-ended",x.returned||"—",x.condition,x.status]),totalLabel:"Active allocations",totalValue:String(assignments.filter(x=>x.status==="Active").length),filterIndex:8,filterLabel:"Status"};
  if(page==="Maintenance History Report")return {title:"Maintenance History",description:"All maintenance schedules and work logs with cost.",headers:["Asset","Work","Type","Frequency","Reported","Due / Completed","Assigned To","Vendor","Estimated","Actual","Status"],rows:maintenance.map(x=>[x.asset,x.title,x.type,x.frequency,x.reported,x.completed||x.nextDue,x.assigned,x.vendor,money(x.estimated),money(x.cost),x.status]),totalLabel:"Maintenance cost",totalValue:money(maintenance.reduce((n,x)=>n+x.cost,0)),filterIndex:10,filterLabel:"Status"};
  if(page==="Warranty Expiry Report")return {title:"Warranty Expiry",description:"Assets with a warranty, soonest expiry first.",headers:["Asset","Tag","Category","Provider","Warranty Expiry","Insurance Provider","Policy","Insurance Expiry","Status"],rows:assets.filter(x=>x.warrantyExpiry).sort((a,b)=>a.warrantyExpiry.localeCompare(b.warrantyExpiry)).map(x=>[x.name,x.tag,x.category,x.warrantyProvider,x.warrantyExpiry,x.insuranceProvider||"—",x.policy||"—",x.insuranceExpiry||"—",x.warrantyExpiry<isoToday()?"Expired":"Active"]),totalLabel:"Covered assets",totalValue:String(assets.filter(x=>x.warrantyExpiry).length),filterIndex:8,filterLabel:"Status"};
  if(page==="Disposal Register Report")return {title:"Disposal Register",description:"Disposed or retired assets with approval and gain or loss.",headers:["Asset","Tag","Method","Date","Recipient","Reason","Book Value","Realised Value","Gain / Loss","Status"],rows:disposals.map(x=>[x.asset,assets.find(a=>a.id===x.assetId)?.tag??"—",x.method,x.date,x.recipient||"—",x.reason,money(x.bookValue),money(x.realised),money(x.realised-x.bookValue),x.status]),totalLabel:"Realised value",totalValue:money(disposals.reduce((n,x)=>n+x.realised,0)),filterIndex:9,filterLabel:"Status"};
  const movements:Array<Array<string|number>>=[
    ...assets.map(x=>[x.purchaseDate,x.tag,x.name,"Registered","Procurement",x.location,x.status]),
    ...assignments.map(x=>[x.returned||x.assigned,assets.find(a=>a.id===x.assetId)?.tag??"—",x.asset,x.returned?"Returned":"Allocated",x.holderType,x.holder,x.status]),
    ...maintenance.map(x=>[x.completed||x.reported,assets.find(a=>a.id===x.assetId)?.tag??"—",x.asset,x.completed?"Maintenance completed":"Maintenance opened",x.type,x.vendor,x.status]),
    ...disposals.map(x=>[x.date,assets.find(a=>a.id===x.assetId)?.tag??"—",x.asset,"Disposal",x.method,x.recipient||"Asset register",x.status]),
  ].sort((a,b)=>String(b[0]).localeCompare(String(a[0])));
  return {title:"Movement Ledger",description:"The full lifecycle event timeline across all assets.",headers:["Date","Tag","Asset","Event","Reference","Destination / Holder","Status"],rows:movements,totalLabel:"Lifecycle events",totalValue:String(movements.length),filterIndex:6,filterLabel:"Status"};
}
function csvDownload(data:ReportData){const escape=(value:string|number)=>`"${String(value).replaceAll('"','""')}"`,csv=[data.headers,...data.rows].map(row=>row.map(escape).join(",")).join("\r\n"),blob=new Blob([`\uFEFF${csv}`],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${data.title.toLowerCase().replaceAll(/[^a-z0-9]+/g,"-")}.csv`;link.style.display="none";document.body.appendChild(link);link.click();link.remove();globalThis.setTimeout(()=>URL.revokeObjectURL(url),1000);}
function pdfDownload(data:ReportData){const bytes=buildAssetReportPdf(data),blob=new Blob([bytes],{type:"application/pdf"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.target="_blank";link.rel="noopener";link.style.display="none";document.body.appendChild(link);link.click();link.remove();globalThis.setTimeout(()=>URL.revokeObjectURL(url),60000);}
function AssetReports({assets,assignments,maintenance,disposals,onPage,notify}:{assets:Asset[];assignments:Assignment[];maintenance:Maintenance[];disposals:Disposal[];onPage:(p:string)=>void;notify:(s:string)=>void}){
  const counts=[assets.length,assets.length,assignments.length,maintenance.length,assets.filter(x=>x.warrantyExpiry).length,disposals.length,assets.length+assignments.length+maintenance.length+disposals.length];
  const descriptions=["Full list of every fixed asset with status and value.","Every posted depreciation period, newest first.","Who holds (or held) each asset.","All maintenance work logs and their cost.","Assets with a warranty, soonest expiry first.","Disposed / retired assets and gain/loss.","The full lifecycle event timeline across all assets."];
  return <><section className={styles.assetReportHero}><div><span>ASSET INTELLIGENCE</span><h2>Reports & Exports</h2><p>Operational, financial and compliance views from one live register.</p></div><div><b>{money(assets.reduce((n,x)=>n+bookValue(x),0))}</b><span>Current book value</span></div></section><section className={styles.assetReportGrid}>{reportPages.map((page,index)=>{const data=reportData(page,assets,assignments,maintenance,disposals);return <article key={page}><i>{["AR","DP","CU","MT","WR","DS","MV"][index]}</i><div><h3>{data.title}</h3><p>{descriptions[index]}</p><small>{counts[index]} records available</small></div><footer><button onClick={()=>onPage(page)}>▦ View</button><button onClick={()=>{pdfDownload(data);notify(`${data.title} PDF opened`);}}>PDF</button><button onClick={()=>{csvDownload(data);notify(`${data.title} CSV downloaded`);}}>CSV</button></footer></article>})}</section></>;
}
function AssetReportDetail({page,assets,assignments,maintenance,disposals,onPage,notify}:{page:string;assets:Asset[];assignments:Assignment[];maintenance:Maintenance[];disposals:Disposal[];onPage:(p:string)=>void;notify:(s:string)=>void}){
  const data=reportData(page as ReportPage,assets,assignments,maintenance,disposals),[search,setSearch]=useState(""),[status,setStatus]=useState("All"),[from,setFrom]=useState(""),[to,setTo]=useState(""),statuses=["All",...new Set(data.rows.map(row=>String(row[data.filterIndex])))];
  const rows=data.rows.filter(row=>{const text=row.join(" ").toLowerCase(),date=String(row.find(cell=>/^\d{4}-\d{2}-\d{2}$/.test(String(cell)))??"");return (!search||text.includes(search.toLowerCase()))&&(status==="All"||String(row[data.filterIndex])===status)&&(!from||!date||date>=from)&&(!to||!date||date<=to);});
  return <><div className={styles.assetReportToolbar}><button onClick={()=>onPage("Asset Reports")}>← All Asset Reports</button><div><button onClick={()=>{pdfDownload({...data,rows});notify(`${data.title} PDF opened`);}}>▣ Export PDF</button><button onClick={()=>{csvDownload({...data,rows});notify(`${data.title} CSV downloaded`);}}>⇩ Export CSV</button></div></div><section className={styles.assetReportTitle}><div><span>HIG SCHOOL · ASSET MANAGEMENT</span><h2>{data.title} <small>{rows.length}</small></h2><p>{data.description}</p></div><aside><span>{data.totalLabel}</span><b>{data.totalValue}</b><small>Generated {new Date().toLocaleDateString("en-IN")}</small></aside></section><section className={styles.assetReportFilters}><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tag, asset, category, holder..."/></label><label>{data.filterLabel}<select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={()=>{setSearch("");setStatus("All");setFrom("");setTo("");}}>Reset</button></section><APanel title={`${data.title} Records`} subtitle={`Showing ${rows.length} of ${data.rows.length} records`}><div className={styles.assetReportTable} style={{"--asset-report-columns":data.headers.length} as React.CSSProperties}><div>{data.headers.map(x=><b key={x}>{x}</b>)}</div>{rows.map((row,index)=><div key={`${page}-${index}`}>{row.map((cell,i)=>i===data.filterIndex?<Badge key={`${cell}-${i}`} value={String(cell)}/>:<span key={`${cell}-${i}`}>{cell}</span>)}</div>)}</div>{!rows.length&&<div className={styles.assetReportEmpty}><b>No matching records</b><span>Change or reset the report filters.</span></div>}<footer className={styles.assetReportFoot}><span>Report generated from the current asset register.</span><strong>{data.totalLabel}: {data.totalValue}</strong></footer></APanel></>;
}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className={styles.assetModalBackdrop} onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section className={styles.assetModal}><header><h2>{title}</h2><button onClick={close}>×</button></header>{children}</section></div>;}
