"use client";

import { FormEvent, useMemo, useState } from "react";
import { buildAssetReportPdf } from "./asset-report-pdf";
import styles from "./school.module.css";

type Student={id:string;admissionNumber:string;rollNumber:string;fullName:string;gender:string;admissionDate:string;className:string;sectionName:string;guardianName:string;guardianPhone:string;status:string};
type Operations={attendance:Array<{studentName:string;className:string;sectionName:string;attendanceDate:string;status:string}>;invoices:Array<{studentName:string;admissionNumber:string;feeType:string;amountPaise:number;paidPaise:number;dueDate:string;status:string}>;payments:Array<{studentName:string;amountPaise:number;method:string;reference:string;paidOn:string}>;metrics:{present:number;absent:number;late:number;attendanceMarked:number;invoicedPaise:number;collectedPaise:number;outstandingPaise:number}};
type Workspace={records:Array<{id:string;moduleKey:string;workflow:string;title:string;recordDate:string;amountPaise:number|null;assignee:string;priority:string;status:string}>;metrics:{total:number;open:number;inProgress:number;completed:number;urgent:number;overdue:number;amountPaise:number}};
type ReportCategory="Finance"|"Academics"|"Student Info"|"HR"|"Attendance"|"Module Reports"|"System Logs";
type ReportDefinition={title:string;description:string;category:ReportCategory;icon:string};
type Props={page:string;students:Student[];operations:Operations;workspace:Workspace;onPage:(page:string)=>void};

const reports:ReportDefinition[]=[
  ...[["Daily Collection","View total daily fee collections with payment modes."],["Fee Type Collection","Breakdown of collected fees by specific fee types."],["Class Wise Collection","Fee collection summaries grouped by classes."],["Fee Dues Report","Detailed list of pending fee dues for students."],["Defaulters List","Identify students with long-standing pending dues."],["Student Ledger","Comprehensive fee transaction history for individual students."],["Income Report","Track all other sources of income and revenue."],["Expense Report","Track all school expenditures and financial outflows."],["Income vs. Expense","Compare total income against total expenses over time."],["Payroll Report","View total salary disbursements and payroll records."],["Monthly Summary","A consolidated month-end financial overview."],["Cancelled Receipts","Audit log of fee receipts that were subsequently cancelled."],["Concession Report","Head-wise list of fee discounts and concessions granted."],["Head-wise Fee Report","Macro snapshot of dues, concessions, and collection per fee head."],["Fees Analysis","Dynamic excel-like report of student payments grouped by Month or Fee Heads."]].map(([title,description],index)=>({title,description,category:"Finance" as const,icon:["DC","FT","CL","DU","DF","SL","IN","EX","IE","PR","MS","CR","CN","HF","FA"][index]})),
  ...[["Exam Marks","Subject-wise marks and grades across different examinations."],["Student Progress","Track individual student performance across multiple terms."],["Class Performance","Aggregate performance and statistics for an entire class."],["Consolidated Performance","School-wide academic standing and comparative analytics."],["CBC Assessment Report","Generate and download Competency Based Curriculum reports."]].map(([title,description],index)=>({title,description,category:"Academics" as const,icon:["EM","SP","CP","CO","CB"][index]})),
  ...[["Student List Report","Comprehensive list of students with advanced filtering."],["Attendance Percentage","Monthly attendance percentage per student."],["Admission Report","Track new student enrollments over any period."],["Total Strength Report","Live class-wise snapshot of boys, girls, and categories."],["Sibling Report","Identify sibling groups based on family contact details."]].map(([title,description],index)=>({title,description,category:"Student Info" as const,icon:["ST","AP","AD","TS","SB"][index]})),
  ...[["Staff List","Directory of all employees, teachers, and administrators."],["Staff Attendance Summary","Monthly attendance records and leave tracking for staff."],["Employee Loans Report","Track active employee loan amounts, EMIs, and paid balances."],["Statutory Compliance Report","Deductions for PF, ESI, PT, and TDS with statutory returns."],["Leave Balance Report","Audit of staff leave types, allocations, and availed days."]].map(([title,description],index)=>({title,description,category:"HR" as const,icon:["SF","SA","LN","SC","LV"][index]})),
  ...[["Student Attendance","Daily register and monthly logs for student attendance."],["Staff Attendance","Daily punch records and status for employees."],["Attendance Live Log","Real-time feed of biometric and app attendance punches."],["Teacher Submission Report","Track whether class teachers submitted daily attendance."]].map(([title,description],index)=>({title,description,category:"Attendance" as const,icon:["AT","ST","LL","TS"][index]})),
  ...[["Library Issues","Track currently issued books and overdue returns."],["Transport List","List of students assigned to specific vehicle routes."],["Hostel Occupancy","Current room allocations and vacant bed availability."],["Inventory Stock","Current stock levels, categories, and item availability."],["Email/SMS Deliverability","Analyze delivery rates and errors for communications."]].map(([title,description],index)=>({title,description,category:"Module Reports" as const,icon:["LB","TR","HO","IN","CM"][index]})),
  ...[["User Login Report","Audit trail of user logins, devices, and IP locations."],["Generated Documents","Archived history of certificates and ID cards."]].map(([title,description],index)=>({title,description,category:"System Logs" as const,icon:["UL","GD"][index]})),
];
const categoryOrder:Array<"All"|ReportCategory>=["All","Finance","Academics","Student Info","HR","Attendance","Module Reports","System Logs"];
const money=(paise:number)=>`₹${Math.round(paise/100).toLocaleString("en-IN")}`;

export function ReportsAnalyticsPage(props:Props){return props.page==="Reports & Analytics"?<ReportsHub onPage={props.onPage}/>:<ReportViewer {...props}/>;}

function ReportsHub({onPage}:{onPage:(page:string)=>void}){
  const [category,setCategory]=useState<"All"|ReportCategory>("All"),[search,setSearch]=useState("");
  const filtered=useMemo(()=>reports.filter(x=>(category==="All"||x.category===category)&&(!search||`${x.title} ${x.description} ${x.category}`.toLowerCase().includes(search.toLowerCase()))),[category,search]);
  return <><header className={styles.reportsHubHeader}><div><span>MANAGEMENT INTELLIGENCE</span><h1>Reports Hub</h1><p>Everything, in one place. Search, filter and open any school report.</p></div><label>⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search reports..."/></label></header><nav className={styles.reportCategoryNav}>{categoryOrder.map(x=>{const count=x==="All"?reports.length:reports.filter(r=>r.category===x).length;return <button className={category===x?styles.reportCategoryActive:""} onClick={()=>setCategory(x)} key={x}>{x} <b>{count}</b></button>})}</nav><section className={styles.reportHubSummary}>{[["41","Reports"],["7","Categories"],["2026-27","Academic session"],["Live","Connected data"]].map(([value,label])=><article key={label}><b>{value}</b><span>{label}</span></article>)}</section><section className={styles.reportCardGrid}>{filtered.map(report=><article key={report.title}><i>{report.icon}</i><div><h2>{report.title}</h2><p>{report.description}</p><span>{report.category}</span></div><button onClick={()=>onPage(report.title)}>Open Report　→</button></article>)}</section>{!filtered.length&&<div className={styles.reportNoResults}><b>No reports found</b><span>Try another keyword or category.</span></div>}</>;
}

type ReportOutput={headers:string[];rows:Array<Array<string|number>>;metrics:Array<[string,string]>};
function outputFor(report:ReportDefinition,{students,operations,workspace}:{students:Student[];operations:Operations;workspace:Workspace}):ReportOutput{
  if(report.category==="Finance"){
    const payments=operations.payments.length?operations.payments:[{studentName:"Aarav Sharma",amountPaise:1850000,method:"UPI",reference:"HIG-PAY-1042",paidOn:"2026-07-24"},{studentName:"Meera Iyer",amountPaise:1250000,method:"Cash",reference:"HIG-PAY-1041",paidOn:"2026-07-23"},{studentName:"Kabir Khan",amountPaise:2200000,method:"Bank Transfer",reference:"HIG-PAY-1040",paidOn:"2026-07-22"}];
    if(report.title.includes("Due")||report.title.includes("Defaulter")||report.title==="Student Ledger"){const invoices=operations.invoices.length?operations.invoices:[{studentName:"Aarav Sharma",admissionNumber:"HIG-2026-018",feeType:"Tuition Fee",amountPaise:3000000,paidPaise:1850000,dueDate:"2026-07-15",status:"partially_paid"},{studentName:"Meera Iyer",admissionNumber:"HIG-2026-017",feeType:"Transport Fee",amountPaise:1800000,paidPaise:800000,dueDate:"2026-07-10",status:"overdue"}];return {headers:["Admission No.","Student","Fee Head","Due Date","Billed","Paid","Balance","Status"],rows:invoices.map(x=>[x.admissionNumber,x.studentName,x.feeType,x.dueDate,money(x.amountPaise),money(x.paidPaise),money(x.amountPaise-x.paidPaise),x.status.replaceAll("_"," ")]),metrics:[["Total billed",money(operations.metrics.invoicedPaise||4800000)],["Collected",money(operations.metrics.collectedPaise||2650000)],["Outstanding",money(operations.metrics.outstandingPaise||2150000)],["Defaulters",String(invoices.filter(x=>x.amountPaise>x.paidPaise).length)]]};}
    return {headers:["Receipt","Date","Student / Source","Payment Mode","Fee Head","Amount","Status"],rows:payments.map((x,i)=>[x.reference||`HIG-RCP-${1042-i}`,x.paidOn,x.studentName,x.method,report.title.includes("Expense")?"Operational Expense":"Tuition Fees",money(x.amountPaise),"Posted"]),metrics:[["Transactions",String(payments.length)],["Gross collection",money(payments.reduce((n,x)=>n+x.amountPaise,0))],["Cash",money(payments.filter(x=>x.method==="Cash").reduce((n,x)=>n+x.amountPaise,0))],["Digital",money(payments.filter(x=>x.method!=="Cash").reduce((n,x)=>n+x.amountPaise,0))]]};
  }
  if(report.category==="Student Info"||report.category==="Academics"){
    const list=students.length?students:[{id:"1",admissionNumber:"HIG-2026-018",rollNumber:"18",fullName:"Aarav Sharma",gender:"male",admissionDate:"2026-04-03",className:"Grade 8",sectionName:"A",guardianName:"Neha Sharma",guardianPhone:"98765 20184",status:"active"}];
    if(report.category==="Academics")return {headers:["Admission No.","Student","Class","English","Mathematics","Science","Total","Grade"],rows:list.map((x,i)=>[x.admissionNumber,x.fullName,`${x.className} ${x.sectionName}`,78+i*2,84-i,81+i,243+i*2,["A","A1","B+"][i%3]]),metrics:[["Students",String(list.length)],["Class average","81.4%"],["Highest","94.0%"],["Pass rate","97.5%"]]};
    return {headers:["Admission No.","Roll","Student","Class","Gender","Guardian","Phone","Admission Date","Status"],rows:list.map(x=>[x.admissionNumber,x.rollNumber,x.fullName,`${x.className} - ${x.sectionName}`,x.gender,x.guardianName,x.guardianPhone,x.admissionDate,x.status]),metrics:[["Students",String(list.length)],["Boys",String(list.filter(x=>x.gender==="male").length)],["Girls",String(list.filter(x=>x.gender==="female").length)],["Active",String(list.filter(x=>x.status==="active").length)]]};
  }
  if(report.category==="Attendance"){
    const attendance=operations.attendance.length?operations.attendance:[{studentName:"Aarav Sharma",className:"Grade 8",sectionName:"A",attendanceDate:"2026-07-26",status:"present"},{studentName:"Meera Iyer",className:"Grade 7",sectionName:"B",attendanceDate:"2026-07-26",status:"late"},{studentName:"Kabir Khan",className:"Grade 9",sectionName:"A",attendanceDate:"2026-07-26",status:"absent"}];
    return {headers:["Date","Person","Class / Department","Section","Punch In","Punch Out","Source","Status"],rows:attendance.map((x,i)=>[x.attendanceDate,x.studentName,x.className,x.sectionName,["08:04","08:11","—"][i%3],["15:05","15:02","—"][i%3],i?"Mobile App":"QR Attendance",x.status]),metrics:[["Marked",String(attendance.length)],["Present",String(attendance.filter(x=>x.status==="present").length)],["Absent",String(attendance.filter(x=>x.status==="absent").length)],["Late",String(attendance.filter(x=>x.status==="late").length)]]};
  }
  if(report.category==="HR"){
    const staff=[["HIG-ST-001","Riya Kapoor","Academic","Senior Teacher","98765 30211","riya@higschool.in","Active"],["HIG-ST-002","Priya Sharma","Finance","Accountant","98912 44031","priya@higschool.in","Active"],["HIG-ST-003","Arjun Verma","Administration","Office Staff","98102 11882","arjun@higschool.in","Active"],["HIG-ST-004","Neha Singh","Mathematics","HOD","98710 55424","neha@higschool.in","On Leave"]];
    return {headers:["Employee ID","Name","Department","Designation","Phone","Email","Status"],rows:staff,metrics:[["Total staff","4"],["Teachers","2"],["Active","3"],["On leave","1"]]};
  }
  if(report.category==="System Logs"){
    const logs=[["26 Jul 2026 09:42","Ankit Yadav · admin@higschool.in","School Admin","103.214.61.22","Chrome 140 · macOS","Success"],["26 Jul 2026 08:11","Riya Kapoor · riya@higschool.in","Teacher","49.36.120.14","Chrome Mobile · Android","Success"],["25 Jul 2026 16:32","Priya Sharma · priya@higschool.in","Staff","117.99.18.45","Edge · Windows","Success"]];
    return {headers:["Date & Time","User (Name & Email)","Role","IP Address","Device / Agent","Status"],rows:logs,metrics:[["Logins today","2"],["Unique users","3"],["Failed attempts","0"],["Active sessions","2"]]};
  }
  const records=workspace.records.length?workspace.records.slice(0,8).map(x=>[x.id.slice(-6).toUpperCase(),x.title,x.workflow,x.assignee||"Unassigned",x.recordDate,x.amountPaise?money(x.amountPaise):"—",x.status]):[["INV-1001","A4 Copier Paper","Inventory Stock","Main Store","2026-07-26","480 units","Available"],["LIB-2084","The Discovery of India","Library Issues","Aarav Sharma","2026-07-18","Due 28 Jul","Issued"],["TRN-014","Route 4 - North Campus","Transport List","Bus HIG-04","2026-07-26","32 students","Active"]];
  return {headers:["Reference","Item / Record","Module","Holder / Location","Date","Value / Quantity","Status"],rows:records,metrics:[["Records",String(records.length)],["Active",String(records.filter(x=>String(x[6]).toLowerCase().includes("active")).length)],["Attention","1"],["Updated","Today"]]};
}

function filterFields(report:ReportDefinition){
  if(report.title==="Daily Collection")return [["Report Type",["Daily Report","Date Range Report","Fee Group Wise Report"]],["Fee Group",["All Fee Groups","Monthly Fees","Admission Fees","Transport Fees"]],["Bank Account",["All Accounts","Cash Account","SBI Bank Account"]]] as const;
  if(report.category==="Academics")return [["Exam",["Term 1 (2026-27)","Term 2 (2026-27)","Half-Yearly Examination"]],["Class",["All Classes","Grade 6","Grade 7","Grade 8","Grade 9","Grade 10"]],["Section",["All Sections","A","B","C"]]] as const;
  if(report.category==="Student Info")return [["Class",["All Classes","Grade 6","Grade 7","Grade 8","Grade 9","Grade 10"]],["Section",["All Sections","A","B","C"]],["Category",["All Categories","General","OBC","SC","ST"]],["Gender",["All Genders","Male","Female","Other"]]] as const;
  if(report.category==="HR")return [["Department",["All Departments","Academic","Finance","Administration","Mathematics"]],["Designation",["All Designations","HOD","Senior Teacher","Accountant","Staff"]]] as const;
  if(report.category==="Attendance")return [["Report Type",["Monthly Register","Daily Report","Biometric Log","Punch In/Out Log"]],["Class",["All Classes","Grade 6","Grade 7","Grade 8","Grade 9","Grade 10"]],["Section",["All Sections","A","B","C"]],["Month",["July","June","May","April"]]] as const;
  if(report.category==="System Logs")return [["User Role",["All Roles","School Admin","Teacher","Staff","Parent","Student"]]] as const;
  return [["Category",["All Categories","Stationery","Lab Supplies","Sports Equipment","Books"]]] as const;
}
function csvDownload(title:string,headers:string[],rows:Array<Array<string|number>>){const esc=(x:string|number)=>`"${String(x).replaceAll('"','""')}"`,csv=[headers,...rows].map(r=>r.map(esc).join(",")).join("\r\n"),url=URL.createObjectURL(new Blob([`\uFEFF${csv}`],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=`${title.toLowerCase().replaceAll(/[^a-z0-9]+/g,"-")}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function pdfOpen(title:string,description:string,headers:string[],rows:Array<Array<string|number>>){const bytes=buildAssetReportPdf({title,description,headers,rows,totalLabel:"Records",totalValue:String(rows.length)}),url=URL.createObjectURL(new Blob([bytes],{type:"application/pdf"})),a=document.createElement("a");a.href=url;a.target="_blank";a.rel="noopener";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}

function ReportViewer({page,students,operations,workspace,onPage}:Props){
  const report=reports.find(x=>x.title===page)??reports[0],data=outputFor(report,{students,operations,workspace}),[generated,setGenerated]=useState(true),[query,setQuery]=useState(""),[toast,setToast]=useState("");
  const rows=data.rows.filter(row=>!query||row.join(" ").toLowerCase().includes(query.toLowerCase()));
  function notify(message:string){setToast(message);setTimeout(()=>setToast(""),2200);}
  function generate(e:FormEvent){e.preventDefault();setGenerated(true);notify(`${report.title} generated`);}
  return <><header className={styles.reportViewerHeader}><button onClick={()=>onPage("Reports & Analytics")}>← Reports Hub</button><div><span>{report.category} · 2026-27</span><h1>{report.title}{report.title.includes("Report")?"":" Report"}</h1><p>{report.description}</p></div><aside><button onClick={()=>{pdfOpen(report.title,report.description,data.headers,rows);notify("PDF opened");}}>PDF</button><button onClick={()=>{csvDownload(report.title,data.headers,rows);notify("CSV downloaded");}}>Export CSV</button></aside></header><section className={styles.reportViewerLayout}><aside className={styles.quickReports}><header><b>Quick Report Links</b><span>41 Reports</span></header>{reports.filter(x=>x.category===report.category).map(x=><button className={x.title===page?styles.quickReportActive:""} onClick={()=>onPage(x.title)} key={x.title}><i>{x.icon}</i><span>{x.title}</span></button>)}</aside><main><form className={styles.reportFilterPanel} onSubmit={generate}><header><h2>Filter Records</h2><p>Choose criteria and generate the report.</p></header><div>{filterFields(report).map(([label,options])=><label key={label}>{label}<select>{options.map(x=><option key={x}>{x}</option>)}</select></label>)}<label>From Date<input type="date" defaultValue="2026-07-01"/></label><label>To Date<input type="date" defaultValue="2026-07-26"/></label><button>Generate Report</button></div></form>{generated&&<><section className={styles.reportMetrics}>{data.metrics.map(([label,value],index)=><article key={label}><i>{["01","02","03","04"][index]}</i><span>{label}</span><b>{value}</b></article>)}</section><article className={styles.reportResultPanel}><header><div><h2>{report.title}</h2><p>Academic session 2026-27 · {rows.length} records</p></div><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search results..."/></label></header><div className={styles.reportResultTable} style={{"--report-columns":data.headers.length} as React.CSSProperties}><div>{data.headers.map(x=><b key={x}>{x}</b>)}</div>{rows.map((row,index)=><div key={`${page}-${index}`}>{row.map((cell,i)=><span key={`${cell}-${i}`}>{cell}</span>)}</div>)}</div><footer><span>Showing {rows.length} records</span><strong>Generated {new Date().toLocaleDateString("en-IN")}</strong></footer></article></>}</main></section>{toast&&<div className={styles.reportToast}>✓ {toast}</div>}</>;
}
